package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class AddBranch extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

    public AddBranch() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblBranchIDError.setVisible(false);
        lblBranchNameError.setVisible(false);
        lblCountryError.setVisible(false);
        lblCityError.setVisible(false);
        lblStreetError.setVisible(false);
        
        dbCon = new myDBCon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBranchID = new javax.swing.JTextField();
        txtBranchName = new javax.swing.JTextField();
        txtBranchCountry = new javax.swing.JTextField();
        lblBranchIDError = new javax.swing.JLabel();
        lblBranchNameError = new javax.swing.JLabel();
        lblCountryError = new javax.swing.JLabel();
        BtnAddNewBranch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtBranchCity = new javax.swing.JTextField();
        txtBranchStreet = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblStreetError = new javax.swing.JLabel();
        lblCityError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Branch");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Branch");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("BRANCH_ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("BRANCH NAME");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("COUNTRY");

        txtBranchID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBranchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchIDActionPerformed(evt);
            }
        });

        txtBranchName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBranchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchNameActionPerformed(evt);
            }
        });

        txtBranchCountry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBranchCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchCountryActionPerformed(evt);
            }
        });

        lblBranchIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblBranchIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblBranchIDError.setText("error label");

        lblBranchNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblBranchNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblBranchNameError.setText("error label");

        lblCountryError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCountryError.setForeground(new java.awt.Color(255, 0, 0));
        lblCountryError.setText("error label");

        BtnAddNewBranch.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        BtnAddNewBranch.setText("Add New");
        BtnAddNewBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddNewBranchActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("CITY");

        txtBranchCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBranchCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchCityActionPerformed(evt);
            }
        });

        txtBranchStreet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBranchStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchStreetActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("STREET");

        lblStreetError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblStreetError.setForeground(new java.awt.Color(255, 0, 0));
        lblStreetError.setText("error label");

        lblCityError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCityError.setForeground(new java.awt.Color(255, 0, 0));
        lblCityError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnAddNewBranch)
                .addGap(340, 340, 340))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBranchCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCountryError, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBranchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBranchStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCityError, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStreetError, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBranchID)
                                    .addComponent(txtBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBranchNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBranchIDError, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBranchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBranchCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountryError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lblCityError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lblStreetError))
                .addGap(18, 18, 18)
                .addComponent(BtnAddNewBranch)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblBranchIDError.setText("");
        lblBranchIDError.setVisible(false);
        lblBranchNameError.setText("");
        lblBranchNameError.setVisible(false);
        lblCountryError.setText("");
        lblCountryError.setVisible(false);
        lblCityError.setText("");
        lblCityError.setVisible(false);
        lblStreetError.setText("");
        lblStreetError.setVisible(false);
    }

    // validate all user entry before sending new branch details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtBranchID.getText().trim().isEmpty() || !isInteger(txtBranchID.getText().trim()) || (Integer.parseInt(txtBranchID.getText().trim())/10 > 9)) {
            if (txtBranchID.getText().trim().isEmpty()) {
                lblBranchIDError.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(txtBranchID.getText().trim())) {
                lblBranchIDError.setText("Invalid. Must be integer.");
            }
            else {
                lblBranchIDError.setText("Invalid. Must be 2 digits.");
            }
            lblBranchIDError.setVisible(true);
            result = false;
        }

        if (txtBranchName.getText().trim().isEmpty() || (txtBranchName.getText().trim().length() > 25)) {
            if (txtBranchName.getText().trim().isEmpty()) {
                lblBranchNameError.setText("Invalid. Cannot be empty.");
            } else if ((txtBranchName.getText().trim().length() > 14)) {
                lblBranchNameError.setText("Invalid. Must be < 26 chars.");
            }
            lblBranchNameError.setVisible(true);
            result = false;
        }

        if (txtBranchCountry.getText().trim().isEmpty() || (txtBranchCountry.getText().trim().length() > 25)) {
            if (txtBranchCountry.getText().trim().isEmpty()) {
                lblCountryError.setText("Invalid. Cannot be empty.");
            } else if (txtBranchCountry.getText().trim().length() > 13) {
                lblCountryError.setText("Invalid. Must be < 26 chars.");
            }
            lblCountryError.setVisible(true);
            result = false;
        }
        
        if (txtBranchCity.getText().trim().isEmpty() || (txtBranchCity.getText().trim().length() > 25)) {
            if (txtBranchCity.getText().trim().isEmpty()) {
                lblCityError.setText("Invalid. Cannot be empty.");
            } else if (txtBranchCity.getText().trim().length() > 13) {
                lblCityError.setText("Invalid. Must be < 26 chars.");
            }
            lblCityError.setVisible(true);
            result = false;
        }
        if (txtBranchStreet.getText().trim().isEmpty() || (txtBranchStreet.getText().trim().length() > 25)) {
            if (txtBranchStreet.getText().trim().isEmpty()) {
                lblStreetError.setText("Invalid. Cannot be empty.");
            } else if (txtBranchStreet.getText().trim().length() > 13) {
                lblStreetError.setText("Invalid. Must be < 26 chars.");
            }
            lblStreetError.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtBranchID.setText("");
        txtBranchName.setText("");
        txtBranchCountry.setText("");
        txtBranchCity.setText("");
        txtBranchStreet.setText("");
    }

    private boolean isDuplicate(int branch_ID) throws SQLException { // checking if a branch ID is used by another department
        boolean isduplicate = false;
        String stmtSQL = "SELECT branch_ID FROM store_branch WHERE branch_ID = " + branch_ID;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }                
    private void txtBranchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchIDActionPerformed

    private void txtBranchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchNameActionPerformed

    private void txtBranchCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchCountryActionPerformed

    private void BtnAddNewBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddNewBranchActionPerformed
        // TODO add your handling code here:
        try {
            if (isValidData() && !isDuplicate(Integer.parseInt(txtBranchID.getText().trim()))) { // if all data is valid and the branch_ID is not duplicate it executes
                String prepSQL = "INSERT INTO store_branch (branch_ID, name, country, city, street) VALUES ("
                        + txtBranchID.getText().trim() + ", "
                        + "'" + txtBranchName.getText().toUpperCase() + "', '"
                        + txtBranchCountry.getText().toUpperCase() + "', '"
                        + txtBranchCity.getText().toUpperCase() + "', '"
                        + txtBranchStreet.getText().toUpperCase() + "')";

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {
                    
                    prepSQL = "SELECT game_ID from game";
                    try (ResultSet r1 = dbCon.executeStatement(prepSQL)) {
                        while (r1.next()) {
                            int game_ID = r1.getInt("game_ID");
                            prepSQL = "INSERT INTO game_copy (game_game_ID, store_branch_branch_ID, num_of_copies) VALUES ("
                                    + game_ID + ","
                                    + txtBranchID.getText().trim() + ", "
                                    + "0)";
                            result = dbCon.executePrepared(prepSQL);
                            if (result < 1) {
                                JOptionPane.showMessageDialog(null, "Error adding game copies to the branch.");
                                break;
                            }
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Error adding game copies to the branches.");
                    }
                    
                    if (result > 0) {
                       javax.swing.JLabel label = new javax.swing.JLabel("New branch added successfully.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        clearInputBoxes(); 
                    }
                    
                } else {
                    
                }

                rs.close();
            } else {
                if (!isValidData()) { // displaying appropriate error message
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else { // displaying appropriate error message
                    javax.swing.JLabel label = new javax.swing.JLabel("branch_ID Already exists. Use a different branch_ID.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    // check validation errors 
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new branch.");
        }
    }//GEN-LAST:event_BtnAddNewBranchActionPerformed

    private void txtBranchCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchCityActionPerformed

    private void txtBranchStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchStreetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddNewBranch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBranchIDError;
    private javax.swing.JLabel lblBranchNameError;
    private javax.swing.JLabel lblCityError;
    private javax.swing.JLabel lblCountryError;
    private javax.swing.JLabel lblStreetError;
    private javax.swing.JTextField txtBranchCity;
    private javax.swing.JTextField txtBranchCountry;
    private javax.swing.JTextField txtBranchID;
    private javax.swing.JTextField txtBranchName;
    private javax.swing.JTextField txtBranchStreet;
    // End of variables declaration//GEN-END:variables
}
