package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


public class AddCustomer extends javax.swing.JFrame {


    myDBCon dbCon;
    ResultSet rs;
    
    public AddCustomer() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblCustomerIDError.setVisible(false);
        lblCustomerNameError.setVisible(false);
        lblCustomerPhoneNumberError.setVisible(false);
        lblCustomerEmailError.setVisible(false);
        
        dbCon = new myDBCon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerPhoneNumber = new javax.swing.JTextField();
        btnAddNewEmp = new javax.swing.JButton();
        lblCustomerIDError = new javax.swing.JLabel();
        lblCustomerPhoneNumberError = new javax.swing.JLabel();
        lblCustomerNameError = new javax.swing.JLabel();
        txtCustomerEmail = new javax.swing.JTextField();
        lblCustomerEmailError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Customer");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Customer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Customer_ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Phone Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Email");

        txtCustomerID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCustomerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCustomerPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCustomerPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerPhoneNumberActionPerformed(evt);
            }
        });

        btnAddNewEmp.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        lblCustomerIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCustomerIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblCustomerIDError.setText("error label");

        lblCustomerPhoneNumberError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCustomerPhoneNumberError.setForeground(new java.awt.Color(255, 0, 0));
        lblCustomerPhoneNumberError.setText("error label");

        lblCustomerNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCustomerNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblCustomerNameError.setText("error label");

        txtCustomerEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCustomerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerEmailActionPerformed(evt);
            }
        });

        lblCustomerEmailError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCustomerEmailError.setForeground(new java.awt.Color(255, 0, 0));
        lblCustomerEmailError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddNewEmp)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtCustomerPhoneNumber)
                                    .addComponent(txtCustomerEmail)
                                    .addComponent(txtCustomerID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCustomerPhoneNumberError, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(lblCustomerEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCustomerNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCustomerIDError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerPhoneNumberError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerEmailError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnAddNewEmp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerPhoneNumberActionPerformed

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblCustomerIDError.setText("");
        lblCustomerIDError.setVisible(false);
        lblCustomerNameError.setText("");
        lblCustomerNameError.setVisible(false);
        lblCustomerPhoneNumberError.setText("");
        lblCustomerPhoneNumberError.setVisible(false);
        lblCustomerEmailError.setText("");
        lblCustomerEmailError.setVisible(false);
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtCustomerID.getText().trim().isEmpty() || !isInteger(txtCustomerID.getText().trim()) || (Integer.parseInt(txtCustomerID.getText().trim()) / 1000 > 9)) {
            if (txtCustomerID.getText().trim().isEmpty()) {
                lblCustomerIDError.setText("Cannot be empty.");
            } else if (!isInteger(txtCustomerID.getText().trim())) {
                lblCustomerIDError.setText("Must be integer.");
            }
            else{
                lblCustomerIDError.setText("Must be 4 digits at most.");
            }
            lblCustomerIDError.setVisible(true);
            result = false;
        }

        if (txtCustomerName.getText().trim().isEmpty() || (txtCustomerName.getText().trim().length() > 25)) {
            if (txtCustomerName.getText().trim().isEmpty()) {
                lblCustomerNameError.setText("Cannot be empty.");
            } else if ((txtCustomerName.getText().trim().length() > 10)) {
                lblCustomerNameError.setText("Must be < 26 chars.");
            }
            lblCustomerNameError.setVisible(true);
            result = false;
        }

        if (txtCustomerPhoneNumber.getText().trim().isEmpty() || !Pattern.matches("^\\+\\d{3}-\\d{2}-\\d{7}$", txtCustomerPhoneNumber.getText().trim())) {
            if (txtCustomerPhoneNumber.getText().trim().isEmpty()) {
                lblCustomerPhoneNumberError.setText("Cannot be empty.");
            } else {
                lblCustomerPhoneNumberError.setText("Phone number must be in the specified format.");
            }
            lblCustomerPhoneNumberError.setVisible(true);
            result = false;
        }
        
        if (txtCustomerEmail.getText().trim().isEmpty() || (txtCustomerEmail.getText().trim().length() > 25)) {
            if (txtCustomerEmail.getText().trim().isEmpty()) {
                lblCustomerEmailError.setText("Cannot be empty.");
            } else if ((txtCustomerEmail.getText().trim().length() > 10)) {
                lblCustomerEmailError.setText("Must be < 26 chars.");
            }
            lblCustomerEmailError.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtCustomerID.setText("");
        txtCustomerName.setText("");
        txtCustomerPhoneNumber.setText("");
        txtCustomerEmail.setText("");
    }

    private boolean isDuplicate(int Customer_ID) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT customer_ID FROM customer WHERE customer_ID = " + Customer_ID;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:

        try {
            /*
                * you need also to verify that the empno is unique and not duplicate 
                *
             */
            if (isValidData() && !isDuplicate(Integer.parseInt(txtCustomerID.getText().trim()))) {
                // if new employee details are valid, then add new employee to DB

                String prepSQL = "INSERT INTO customer (customer_ID, name, phone_number, email) VALUES (" 
                        + txtCustomerID.getText().trim() + ", "
                        + "'" + txtCustomerName.getText().toUpperCase() + "', "
                        + "'" + txtCustomerPhoneNumber.getText() + "', "
                        + "'" + txtCustomerEmail.getText() + "')";

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New customer added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }

                rs.close();
            } else {
                if (!isDuplicate(Integer.parseInt(txtCustomerID.getText().trim()))) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    javax.swing.JLabel label = new javax.swing.JLabel("customer_ID Already exists. Use a different customer_ID.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    // check validation errors 
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new customer.");
        }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    private void txtCustomerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCustomerEmailError;
    private javax.swing.JLabel lblCustomerIDError;
    private javax.swing.JLabel lblCustomerNameError;
    private javax.swing.JLabel lblCustomerPhoneNumberError;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
