package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class AddDeveloper extends javax.swing.JFrame {


    myDBCon dbCon;
    ResultSet rs;
    
    public AddDeveloper() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblDeveloperIDError.setVisible(false);
        lblDeveloperNameError.setVisible(false);
        lblDeveloperEmailError.setVisible(false);
        
        dbCon = new myDBCon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDeveloperID = new javax.swing.JTextField();
        txtDeveloperName = new javax.swing.JTextField();
        txtDeveloperEmail = new javax.swing.JTextField();
        btnAddNewDeveloper = new javax.swing.JButton();
        lblDeveloperIDError = new javax.swing.JLabel();
        lblDeveloperEmailError = new javax.swing.JLabel();
        lblDeveloperNameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Developer");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Developer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Developer_ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Developer Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Email");

        txtDeveloperID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtDeveloperName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtDeveloperEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDeveloperEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeveloperEmailActionPerformed(evt);
            }
        });

        btnAddNewDeveloper.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewDeveloper.setText("Add New");
        btnAddNewDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDeveloperActionPerformed(evt);
            }
        });

        lblDeveloperIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDeveloperIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblDeveloperIDError.setText("error label");

        lblDeveloperEmailError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDeveloperEmailError.setForeground(new java.awt.Color(255, 0, 0));
        lblDeveloperEmailError.setText("error label");

        lblDeveloperNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDeveloperNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblDeveloperNameError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDeveloperName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtDeveloperEmail)
                                    .addComponent(txtDeveloperID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDeveloperEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(lblDeveloperNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDeveloperIDError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnAddNewDeveloper)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDeveloperID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeveloperIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDeveloperName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeveloperNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDeveloperEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeveloperEmailError))
                .addGap(30, 30, 30)
                .addComponent(btnAddNewDeveloper)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblDeveloperIDError.setText("");
        lblDeveloperIDError.setVisible(false);
        lblDeveloperNameError.setText("");
        lblDeveloperNameError.setVisible(false);
        lblDeveloperEmailError.setText("");
        lblDeveloperEmailError.setVisible(false);
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtDeveloperID.getText().trim().isEmpty() || !isInteger(txtDeveloperID.getText().trim()) || (Integer.parseInt(txtDeveloperID.getText().trim()) / 1000 > 9)) {
            if (txtDeveloperID.getText().trim().isEmpty()) {
                lblDeveloperIDError.setText("Cannot be empty.");
            } else if (!isInteger(txtDeveloperID.getText().trim())) {
                lblDeveloperIDError.setText("Must be integer.");
            }
            else{
                lblDeveloperIDError.setText("Must be 4 digits at most.");
            }
            lblDeveloperIDError.setVisible(true);
            result = false;
        }

        if (txtDeveloperName.getText().trim().isEmpty() || (txtDeveloperName.getText().trim().length() > 25)) {
            if (txtDeveloperName.getText().trim().isEmpty()) {
                lblDeveloperNameError.setText("Cannot be empty.");
            } else if ((txtDeveloperName.getText().trim().length() > 10)) {
                lblDeveloperNameError.setText("Must be < 26 chars.");
            }
            lblDeveloperNameError.setVisible(true);
            result = false;
        }

        if (txtDeveloperEmail.getText().trim().isEmpty() || (txtDeveloperEmail.getText().trim().length() > 25)) {
            if (txtDeveloperEmail.getText().trim().isEmpty()) {
                lblDeveloperEmailError.setText("Cannot be empty.");
            } else {
                lblDeveloperEmailError.setText("Must be < 26 chars.");
            }
            lblDeveloperEmailError.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtDeveloperID.setText("");
        txtDeveloperName.setText("");
        txtDeveloperEmail.setText("");
    }

    private boolean isDuplicate(int developer_ID) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT developer_ID FROM developer WHERE developer_ID = " + developer_ID;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    private void btnAddNewDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDeveloperActionPerformed
        // TODO add your handling code here:

        try {
            if (isValidData() && isInteger(txtDeveloperID.getText().trim()) && !isDuplicate(Integer.parseInt(txtDeveloperID.getText().trim()))) {
                // if new developer details are valid, then add new developer to DB

                String prepSQL = "INSERT INTO developer (developer_ID, name, email) VALUES (" 
                        + txtDeveloperID.getText().trim() + ", "
                        + "'" + txtDeveloperName.getText().toUpperCase() + "', "
                        + "'" + txtDeveloperEmail.getText() + "')";
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {
                    
                    javax.swing.JLabel label = new javax.swing.JLabel("New developer added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }

                rs.close();
            } else {
                if (!isInteger(txtDeveloperID.getText().trim()) || !isDuplicate(Integer.parseInt(txtDeveloperID.getText().trim()))) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    javax.swing.JLabel label = new javax.swing.JLabel("developer_ID Already exists. Use a different developer_ID.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    // check validation errors 
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new developer.");
        }
    }//GEN-LAST:event_btnAddNewDeveloperActionPerformed

    private void txtDeveloperEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeveloperEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeveloperEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewDeveloper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDeveloperEmailError;
    private javax.swing.JLabel lblDeveloperIDError;
    private javax.swing.JLabel lblDeveloperNameError;
    private javax.swing.JTextField txtDeveloperEmail;
    private javax.swing.JTextField txtDeveloperID;
    private javax.swing.JTextField txtDeveloperName;
    // End of variables declaration//GEN-END:variables
}
