package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class AddGame extends javax.swing.JFrame {


    myDBCon dbCon;
    ResultSet rs;
    
    public AddGame() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblGameIDError.setVisible(false);
        lblGameTitleError.setVisible(false);
        lblGameRentalPriceError.setVisible(false);
        try {
            dbCon = new myDBCon();
            rs = dbCon.executeStatement("SELECT name FROM publisher ORDER BY name ASC");
            // populate publisher list
            // populate publisher combo box
            while (rs.next()) {
                cmbPublisher.addItem(rs.getString("name"));
            }
            rs.close();
            rs = dbCon.executeStatement("SELECT developer_ID FROM developer ORDER BY developer_ID ASC");
            DefaultListModel<String> devList = new DefaultListModel<>();
            while (rs.next()) {
                devList.addElement(rs.getString("developer_ID"));
            }
            jListDeveloper.setModel(devList);
            rs.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGameID = new javax.swing.JTextField();
        txtGameTitle = new javax.swing.JTextField();
        txtGameRentalPrice = new javax.swing.JTextField();
        btnAddNewGame = new javax.swing.JButton();
        lblGameIDError = new javax.swing.JLabel();
        lblGameRentalPriceError = new javax.swing.JLabel();
        lblGameTitleError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbPublisher = new javax.swing.JComboBox<>();
        jScrollPaneDeveloper = new javax.swing.JScrollPane();
        jListDeveloper = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Game");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Game");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Game ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Game Title");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Rental Price");

        txtGameID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGameTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGameRentalPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGameRentalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGameRentalPriceActionPerformed(evt);
            }
        });

        btnAddNewGame.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewGame.setText("Add New");
        btnAddNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewGameActionPerformed(evt);
            }
        });

        lblGameIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblGameIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblGameIDError.setText("error label");

        lblGameRentalPriceError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblGameRentalPriceError.setForeground(new java.awt.Color(255, 0, 0));
        lblGameRentalPriceError.setText("error label");

        lblGameTitleError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblGameTitleError.setForeground(new java.awt.Color(255, 0, 0));
        lblGameTitleError.setText("error label");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Publisher");

        jScrollPaneDeveloper.setViewportView(jListDeveloper);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Developer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtGameID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGameIDError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGameTitleError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtGameRentalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGameRentalPriceError, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addGap(193, 193, 193))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(btnAddNewGame)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGameID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGameIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGameTitleError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGameRentalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGameRentalPriceError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6)))
                .addGap(62, 62, 62)
                .addComponent(btnAddNewGame)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblGameIDError.setText("");
        lblGameIDError.setVisible(false);
        lblGameTitleError.setText("");
        lblGameTitleError.setVisible(false);
        lblGameRentalPriceError.setText("");
        lblGameRentalPriceError.setVisible(false);
    }

    // validate all user entry before sending new game details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtGameID.getText().trim().isEmpty() || !isInteger(txtGameID.getText().trim()) || (Integer.parseInt(txtGameID.getText().trim()) / 1000 > 9)) {
            if (txtGameID.getText().trim().isEmpty()) {
                lblGameIDError.setText("Cannot be empty.");
            } else if (!isInteger(txtGameID.getText().trim())) {
                lblGameIDError.setText("Must be integer.");
            }
            else{
                lblGameIDError.setText("Must be 4 digits at most.");
            }
            lblGameIDError.setVisible(true);
            result = false;
        }

        if (txtGameTitle.getText().trim().isEmpty() || (txtGameTitle.getText().trim().length() > 50)) {
            if (txtGameTitle.getText().trim().isEmpty()) {
                lblGameTitleError.setText("Cannot be empty.");
            } else {
                lblGameTitleError.setText("Must be < 50 chars.");
            }
            lblGameTitleError.setVisible(true);
            result = false;
        }

        if (txtGameRentalPrice.getText().trim().isEmpty() || !(isInteger(txtGameRentalPrice.getText().trim()) || isDouble(txtGameRentalPrice.getText().trim())) || (Double.parseDouble(txtGameRentalPrice.getText().trim()) / 1000 > 9 )) {
            if (txtGameRentalPrice.getText().trim().isEmpty()) {
                lblGameRentalPriceError.setText("Cannot be empty.");
            } else if (!(isInteger(txtGameRentalPrice.getText().trim()) || isDouble(txtGameRentalPrice.getText().trim()))) {
                lblGameRentalPriceError.setText("Must be a number.");
            } 
            else if (Double.parseDouble(txtGameRentalPrice.getText().trim()) / 1000 > 9){
                lblGameRentalPriceError.setText("Must less than 1000.");
            }
            lblGameRentalPriceError.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtGameID.setText("");
        txtGameTitle.setText("");
        txtGameRentalPrice.setText("");
        jListDeveloper.clearSelection();
    }

    private boolean isDuplicate(int game_ID) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT game_ID FROM game WHERE game_ID = " + game_ID;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    private void btnAddNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewGameActionPerformed
        // TODO add your handling code here:

        try {
            if (isValidData() && !isDuplicate(Integer.parseInt(txtGameID.getText().trim()))) {
                // if new game details are valid, then add new game to DB
                
                String prepSQL = "INSERT INTO game (game_ID, title, rental_price, PUBLISHER_NAME) VALUES (" 
                        + txtGameID.getText().trim() + ", "
                        + "'" + txtGameTitle.getText().toUpperCase() + "', "
                        + txtGameRentalPrice.getText().trim() + ", "
                        + "'" + cmbPublisher.getSelectedItem().toString() + "')";
                int result = dbCon.executePrepared(prepSQL);
                
                if (result > 0) {
                    try {
                        for (int i = 0; i < jListDeveloper.getSelectedValuesList().size(); i++) {
                            String dev_ID = jListDeveloper.getSelectedValuesList().get(i);
                            prepSQL = "INSERT INTO develops (game_ID, developer_ID) VALUES ("
                                    + txtGameID.getText().trim()
                                    + ", " + dev_ID.trim() + ")";
                            result = dbCon.executePrepared(prepSQL);
                            if (result < 1) {
                                JOptionPane.showMessageDialog(null, "Error adding developers to the game.");
                                break;
                            }
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Error adding developers to the game.");
                    }
                    prepSQL = "SELECT branch_ID from store_branch";
                    try (ResultSet r1 = dbCon.executeStatement(prepSQL)) {
                        while (r1.next()) {
                            int branch_ID = r1.getInt("branch_ID");
                            prepSQL = "INSERT INTO game_copy (store_branch_branch_ID, game_game_ID, num_of_copies) VALUES ("
                                    + branch_ID + ","
                                    + txtGameID.getText().trim() + ", "
                                    + "0)";
                            result = dbCon.executePrepared(prepSQL);
                            if (result < 1) {
                                JOptionPane.showMessageDialog(null, "Error adding game copies to the branches.");
                                break;
                            }
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Error adding game copies to the branches.");
                    }
                    /*prepSQL = "INSERT INTO develops (game_ID, developer_ID) VALUES (" 
                        + txtGameID.getText().trim() + ", "
                        + "'" + txtGameTitle.getText().toUpperCase() + "', "
                        + txtGameRentalPrice.getText().trim() + ", "
                        + "'" + cmbPublisher.getSelectedItem().toString() + "')";
                    
                    result = dbCon.executePrepared(prepSQL);
                    */
                    javax.swing.JLabel label = new javax.swing.JLabel("New game added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }

                rs.close();
            } else {
                if (!isDuplicate(Integer.parseInt(txtGameID.getText().trim()))) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    javax.swing.JLabel label = new javax.swing.JLabel("game_ID Already exists. Use a different game_ID.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    // check validation errors 
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new game.");
        }
    }//GEN-LAST:event_btnAddNewGameActionPerformed

    private void txtGameRentalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGameRentalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGameRentalPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewGame;
    private javax.swing.JComboBox<String> cmbPublisher;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListDeveloper;
    private javax.swing.JScrollPane jScrollPaneDeveloper;
    private javax.swing.JLabel lblGameIDError;
    private javax.swing.JLabel lblGameRentalPriceError;
    private javax.swing.JLabel lblGameTitleError;
    private javax.swing.JTextField txtGameID;
    private javax.swing.JTextField txtGameRentalPrice;
    private javax.swing.JTextField txtGameTitle;
    // End of variables declaration//GEN-END:variables
}
