package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class AddPublisher extends javax.swing.JFrame {


    myDBCon dbCon;
    ResultSet rs;
    
    public AddPublisher() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblPublisherNameError.setVisible(false);
        lblPublisherCountryError.setVisible(false);
        lblPublisherCityError.setVisible(false);
        lblPublisherStreetError.setVisible(false);
        lblPublisherPhoneNumberError.setVisible(false);
        lblPublisherEmailError.setVisible(false);
        
        dbCon = new myDBCon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPublisherName = new javax.swing.JTextField();
        txtPublisherCountry = new javax.swing.JTextField();
        txtPublisherPhoneNumber = new javax.swing.JTextField();
        btnAddNewPublisher = new javax.swing.JButton();
        lblPublisherNameError = new javax.swing.JLabel();
        lblPublisherPhoneNumberError = new javax.swing.JLabel();
        lblPublisherCountryError = new javax.swing.JLabel();
        txtPublisherEmail = new javax.swing.JTextField();
        lblPublisherEmailError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPublisherCity = new javax.swing.JTextField();
        lblPublisherCityError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPublisherStreet = new javax.swing.JTextField();
        lblPublisherStreetError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Publisher");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Publisher");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Publisher Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Country");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Phone Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Email");

        txtPublisherName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtPublisherCountry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtPublisherPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPublisherPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPublisherPhoneNumberActionPerformed(evt);
            }
        });

        btnAddNewPublisher.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewPublisher.setText("Add New");
        btnAddNewPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPublisherActionPerformed(evt);
            }
        });

        lblPublisherNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherNameError.setText("error label");

        lblPublisherPhoneNumberError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherPhoneNumberError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherPhoneNumberError.setText("error label");

        lblPublisherCountryError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherCountryError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherCountryError.setText("error label");

        txtPublisherEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPublisherEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPublisherEmailActionPerformed(evt);
            }
        });

        lblPublisherEmailError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherEmailError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherEmailError.setText("error label");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("City");

        txtPublisherCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblPublisherCityError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherCityError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherCityError.setText("error label");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Street");

        txtPublisherStreet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblPublisherStreetError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherStreetError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherStreetError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddNewPublisher)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPublisherCountry, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPublisherStreet, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPublisherCity, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(txtPublisherName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPublisherNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPublisherCountryError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPublisherCityError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPublisherStreetError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPublisherEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPublisherPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPublisherPhoneNumberError, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(lblPublisherEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPublisherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublisherNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPublisherCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublisherCountryError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPublisherCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublisherCityError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtPublisherStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPublisherStreetError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPublisherPhoneNumberError)
                        .addComponent(txtPublisherPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPublisherEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublisherEmailError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnAddNewPublisher)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPublisherPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPublisherPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPublisherPhoneNumberActionPerformed

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblPublisherNameError.setText("");
        lblPublisherNameError.setVisible(false);
        lblPublisherCountryError.setText("");
        lblPublisherCountryError.setVisible(false);
        lblPublisherCityError.setText("");
        lblPublisherCityError.setVisible(false);
        lblPublisherStreetError.setText("");
        lblPublisherStreetError.setVisible(false);
        lblPublisherPhoneNumberError.setText("");
        lblPublisherPhoneNumberError.setVisible(false);
        lblPublisherEmailError.setText("");
        lblPublisherEmailError.setVisible(false);
    }

    // validate all user entry before sending new publisher details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtPublisherName.getText().trim().isEmpty() || (txtPublisherName.getText().trim().length() > 25)) {
            if (txtPublisherName.getText().trim().isEmpty()) {
                lblPublisherNameError.setText("Cannot be empty.");
            } else if ((txtPublisherName.getText().trim().length() > 10)) {
                lblPublisherNameError.setText("Must be < 26 chars.");
            }
            lblPublisherNameError.setVisible(true);
            result = false;
        }

        if (txtPublisherCountry.getText().trim().isEmpty() || (txtPublisherCountry.getText().trim().length() > 25)) {
            if (txtPublisherCountry.getText().trim().isEmpty()) {
                lblPublisherCountryError.setText("Cannot be empty.");
            } else if ((txtPublisherCountry.getText().trim().length() > 10)) {
                lblPublisherCountryError.setText("Must be < 26 chars.");
            }
            lblPublisherCountryError.setVisible(true);
            result = false;
        }
        
        if (txtPublisherCity.getText().trim().isEmpty() || (txtPublisherCity.getText().trim().length() > 25)) {
            if (txtPublisherCity.getText().trim().isEmpty()) {
                lblPublisherCityError.setText("Cannot be empty.");
            } else if ((txtPublisherCity.getText().trim().length() > 10)) {
                lblPublisherCityError.setText("Must be < 26 chars.");
            }
            lblPublisherCityError.setVisible(true);
            result = false;
        }
        
        if (txtPublisherStreet.getText().trim().isEmpty() || (txtPublisherStreet.getText().trim().length() > 25)) {
            if (txtPublisherStreet.getText().trim().isEmpty()) {
                lblPublisherStreetError.setText("Cannot be empty.");
            } else if ((txtPublisherStreet.getText().trim().length() > 10)) {
                lblPublisherStreetError.setText("Must be < 26 chars.");
            }
            lblPublisherStreetError.setVisible(true);
            result = false;
        }

        if (txtPublisherPhoneNumber.getText().trim().isEmpty() || !Pattern.matches("^\\+\\d{3}-\\d{2}-\\d{7}$", txtPublisherPhoneNumber.getText().trim())) {
            if (txtPublisherPhoneNumber.getText().trim().isEmpty()) {
                lblPublisherPhoneNumberError.setText("Cannot be empty.");
            } else {
                lblPublisherPhoneNumberError.setText("Phone number must be in the specified format.");
            }
            lblPublisherPhoneNumberError.setVisible(true);
            result = false;
        }
        
        if (txtPublisherEmail.getText().trim().isEmpty() || (txtPublisherEmail.getText().trim().length() > 25)) {
            if (txtPublisherEmail.getText().trim().isEmpty()) {
                lblPublisherEmailError.setText("Cannot be empty.");
            } else if ((txtPublisherEmail.getText().trim().length() > 10)) {
                lblPublisherEmailError.setText("Must be < 26 chars.");
            }
            lblPublisherEmailError.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtPublisherName.setText("");
        txtPublisherCountry.setText("");
        txtPublisherCity.setText("");
        txtPublisherStreet.setText("");
        txtPublisherPhoneNumber.setText("");
        txtPublisherEmail.setText("");
    }

    private boolean isDuplicate(String publisher_name) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT name FROM publisher WHERE name LIKE '" + publisher_name + "'";
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    private void btnAddNewPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPublisherActionPerformed
        // TODO add your handling code here:

        try {
            /*
                * you need also to verify that the publsiher name is unique and not duplicate 
                *
             */
            if (isValidData() && !isDuplicate(txtPublisherName.getText())) {
                // if new publisher details are valid, then add new publisher to DB

                String prepSQL = "INSERT INTO publisher (name, country, city, street, phone_number, email) VALUES (" 
                        + "'" + txtPublisherName.getText().trim().toUpperCase() + "', "
                        + "'" + txtPublisherCountry.getText().trim().toUpperCase() + "', "
                        + "'" + txtPublisherCity.getText().trim().toUpperCase() + "', "
                        + "'" + txtPublisherStreet.getText().trim().toUpperCase() + "', "
                        + "'" + txtPublisherPhoneNumber.getText().trim() + "', "
                        + "'" + txtPublisherEmail.getText().trim() + "')";
                
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("New publisher added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }
                DefaultListModel dlm = new DefaultListModel();
                dlm.addElement(txtPublisherName);
                rs.close();
            } else {
                if (!isDuplicate(txtPublisherName.getText())) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    javax.swing.JLabel label = new javax.swing.JLabel("publisher_name Already exists. Use a different publsiher_name.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    // check validation errors 
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new publisher.");
        }
    }//GEN-LAST:event_btnAddNewPublisherActionPerformed

    private void txtPublisherEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPublisherEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPublisherEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewPublisher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPublisherCityError;
    private javax.swing.JLabel lblPublisherCountryError;
    private javax.swing.JLabel lblPublisherEmailError;
    private javax.swing.JLabel lblPublisherNameError;
    private javax.swing.JLabel lblPublisherPhoneNumberError;
    private javax.swing.JLabel lblPublisherStreetError;
    private javax.swing.JTextField txtPublisherCity;
    private javax.swing.JTextField txtPublisherCountry;
    private javax.swing.JTextField txtPublisherEmail;
    private javax.swing.JTextField txtPublisherName;
    private javax.swing.JTextField txtPublisherPhoneNumber;
    private javax.swing.JTextField txtPublisherStreet;
    // End of variables declaration//GEN-END:variables
}
