package CMP320Project;

/**
 *
 * @author mcheh
 */
public class AdminMenu extends Menu {
    
    /**
     * Creates new form NewAdminMenu
     */
    public AdminMenu(LoginUser user) {
        luser = user;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuItemLogout = new javax.swing.JMenuItem();
        MenuItemExit = new javax.swing.JMenuItem();
        MenuBranch = new javax.swing.JMenu();
        MenuItemAddBranch = new javax.swing.JMenuItem();
        MenuItemUpdateDeleteBranch = new javax.swing.JMenuItem();
        MenuItemManageGameCopies = new javax.swing.JMenuItem();
        MenuPublisher = new javax.swing.JMenu();
        MenuItemAddPublisher = new javax.swing.JMenuItem();
        MenuItemUpdateDeletePublisher = new javax.swing.JMenuItem();
        MenuDeveloper = new javax.swing.JMenu();
        MenuItemAddDeveloper = new javax.swing.JMenuItem();
        MenuItemUpdateDeleteDeveloper = new javax.swing.JMenuItem();
        MenuGame = new javax.swing.JMenu();
        MenuItemAddGame = new javax.swing.JMenuItem();
        MenuItemUpdateDeleteGame = new javax.swing.JMenuItem();
        MenuCustomer = new javax.swing.JMenu();
        MenuItemAddCustomer = new javax.swing.JMenuItem();
        MenuItemUpdateDeleteCustomer = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenu();
        MenuItemAddUser = new javax.swing.JMenuItem();
        MenuItemUpdateDelUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Menu");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CMP320Project/gamestore.jpg"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        MenuFile.setText("File");
        MenuFile.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileActionPerformed(evt);
            }
        });

        MenuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemLogout.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CMP320Project/logout.png"))); // NOI18N
        MenuItemLogout.setText("Logout");
        MenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogoutActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemLogout);

        MenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemExit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CMP320Project/close.png"))); // NOI18N
        MenuItemExit.setText("Exit");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemExit);

        jMenuBar1.add(MenuFile);

        MenuBranch.setText("Branch");
        MenuBranch.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        MenuItemAddBranch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemAddBranch.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemAddBranch.setText("Add New Branch");
        MenuItemAddBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddBranchActionPerformed(evt);
            }
        });
        MenuBranch.add(MenuItemAddBranch);

        MenuItemUpdateDeleteBranch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemUpdateDeleteBranch.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemUpdateDeleteBranch.setText("Update/Delete Branch");
        MenuItemUpdateDeleteBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUpdateDeleteBranchActionPerformed(evt);
            }
        });
        MenuBranch.add(MenuItemUpdateDeleteBranch);

        MenuItemManageGameCopies.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemManageGameCopies.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemManageGameCopies.setText("Manage Game Copies");
        MenuItemManageGameCopies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemManageGameCopiesActionPerformed(evt);
            }
        });
        MenuBranch.add(MenuItemManageGameCopies);

        jMenuBar1.add(MenuBranch);

        MenuPublisher.setText("Publisher");
        MenuPublisher.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        MenuItemAddPublisher.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemAddPublisher.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemAddPublisher.setText("Add New Publisher");
        MenuItemAddPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddPublisherActionPerformed(evt);
            }
        });
        MenuPublisher.add(MenuItemAddPublisher);

        MenuItemUpdateDeletePublisher.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemUpdateDeletePublisher.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemUpdateDeletePublisher.setText("Update/Delete Publisher");
        MenuItemUpdateDeletePublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUpdateDeletePublisherActionPerformed(evt);
            }
        });
        MenuPublisher.add(MenuItemUpdateDeletePublisher);

        jMenuBar1.add(MenuPublisher);

        MenuDeveloper.setText("Developer");
        MenuDeveloper.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        MenuItemAddDeveloper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemAddDeveloper.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemAddDeveloper.setText("Add New Developer");
        MenuItemAddDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddDeveloperActionPerformed(evt);
            }
        });
        MenuDeveloper.add(MenuItemAddDeveloper);

        MenuItemUpdateDeleteDeveloper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemUpdateDeleteDeveloper.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemUpdateDeleteDeveloper.setText("Update/Delete Developer");
        MenuItemUpdateDeleteDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUpdateDeleteDeveloperActionPerformed(evt);
            }
        });
        MenuDeveloper.add(MenuItemUpdateDeleteDeveloper);

        jMenuBar1.add(MenuDeveloper);

        MenuGame.setText("Game");
        MenuGame.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        MenuItemAddGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemAddGame.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemAddGame.setText("Add New Game");
        MenuItemAddGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddGameActionPerformed(evt);
            }
        });
        MenuGame.add(MenuItemAddGame);

        MenuItemUpdateDeleteGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemUpdateDeleteGame.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemUpdateDeleteGame.setText("Update/Delete Game");
        MenuItemUpdateDeleteGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUpdateDeleteGameActionPerformed(evt);
            }
        });
        MenuGame.add(MenuItemUpdateDeleteGame);

        jMenuBar1.add(MenuGame);

        MenuCustomer.setText("Customer");
        MenuCustomer.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        MenuItemAddCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemAddCustomer.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemAddCustomer.setText("Add New Customer");
        MenuItemAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddCustomerActionPerformed(evt);
            }
        });
        MenuCustomer.add(MenuItemAddCustomer);

        MenuItemUpdateDeleteCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemUpdateDeleteCustomer.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemUpdateDeleteCustomer.setText("Update/Delete Customer");
        MenuItemUpdateDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUpdateDeleteCustomerActionPerformed(evt);
            }
        });
        MenuCustomer.add(MenuItemUpdateDeleteCustomer);

        jMenuBar1.add(MenuCustomer);

        menuUser.setText("User");
        menuUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        MenuItemAddUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemAddUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemAddUser.setText("Add New User");
        MenuItemAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddUserActionPerformed(evt);
            }
        });
        menuUser.add(MenuItemAddUser);

        MenuItemUpdateDelUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemUpdateDelUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemUpdateDelUser.setText("Update/Delete User");
        MenuItemUpdateDelUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUpdateDelUserActionPerformed(evt);
            }
        });
        menuUser.add(MenuItemUpdateDelUser);

        jMenuBar1.add(menuUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogoutActionPerformed
        // TODO add your handling code here:
        (new LoginForm()).setVisible(true);
        this.dispose(); // the Menu form is disposed ONLY when the currently logged in user logs out
    }//GEN-LAST:event_MenuItemLogoutActionPerformed

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuItemExitActionPerformed

    private void MenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFileActionPerformed

    private void MenuItemAddBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddBranchActionPerformed
        // TODO add your handling code here:
        (new AddBranch()).setVisible(true);
    }//GEN-LAST:event_MenuItemAddBranchActionPerformed

    private void MenuItemUpdateDeleteBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUpdateDeleteBranchActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteBranch()).setVisible(true);
    }//GEN-LAST:event_MenuItemUpdateDeleteBranchActionPerformed

    private void MenuItemManageGameCopiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemManageGameCopiesActionPerformed
        // TODO add your handling code here:
        (new ManageGameCopies()).setVisible(true);
    }//GEN-LAST:event_MenuItemManageGameCopiesActionPerformed

    private void MenuItemAddPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddPublisherActionPerformed
        // TODO add your handling code here:
        (new AddPublisher()).setVisible(true);
    }//GEN-LAST:event_MenuItemAddPublisherActionPerformed

    private void MenuItemUpdateDeletePublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUpdateDeletePublisherActionPerformed
        // TODO add your handling code here:
        (new UpdateDeletePublisher()).setVisible(true);
    }//GEN-LAST:event_MenuItemUpdateDeletePublisherActionPerformed

    private void MenuItemAddDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddDeveloperActionPerformed
        // TODO add your handling code here:
        (new AddDeveloper()).setVisible(true);
    }//GEN-LAST:event_MenuItemAddDeveloperActionPerformed

    private void MenuItemUpdateDeleteDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUpdateDeleteDeveloperActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteDeveloper()).setVisible(true);
    }//GEN-LAST:event_MenuItemUpdateDeleteDeveloperActionPerformed

    private void MenuItemAddGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddGameActionPerformed
        // TODO add your handling code here:
        (new AddGame()).setVisible(true);
    }//GEN-LAST:event_MenuItemAddGameActionPerformed

    private void MenuItemUpdateDeleteGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUpdateDeleteGameActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteGame()).setVisible(true);
    }//GEN-LAST:event_MenuItemUpdateDeleteGameActionPerformed

    private void MenuItemAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddCustomerActionPerformed
        // TODO add your handling code here:
        (new AddCustomer()).setVisible(true);
    }//GEN-LAST:event_MenuItemAddCustomerActionPerformed

    private void MenuItemUpdateDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUpdateDeleteCustomerActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteCustomer()).setVisible(true);
    }//GEN-LAST:event_MenuItemUpdateDeleteCustomerActionPerformed

    private void MenuItemAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddUserActionPerformed
        // TODO add your handling code here:
        (new AddNewLoginUser()).setVisible(true);
    }//GEN-LAST:event_MenuItemAddUserActionPerformed

    private void MenuItemUpdateDelUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUpdateDelUserActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteLoginUser()).setVisible(true);
    }//GEN-LAST:event_MenuItemUpdateDelUserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBranch;
    private javax.swing.JMenu MenuCustomer;
    private javax.swing.JMenu MenuDeveloper;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuGame;
    private javax.swing.JMenuItem MenuItemAddBranch;
    private javax.swing.JMenuItem MenuItemAddCustomer;
    private javax.swing.JMenuItem MenuItemAddDeveloper;
    private javax.swing.JMenuItem MenuItemAddGame;
    private javax.swing.JMenuItem MenuItemAddPublisher;
    private javax.swing.JMenuItem MenuItemAddUser;
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JMenuItem MenuItemLogout;
    private javax.swing.JMenuItem MenuItemManageGameCopies;
    private javax.swing.JMenuItem MenuItemUpdateDelUser;
    private javax.swing.JMenuItem MenuItemUpdateDeleteBranch;
    private javax.swing.JMenuItem MenuItemUpdateDeleteCustomer;
    private javax.swing.JMenuItem MenuItemUpdateDeleteDeveloper;
    private javax.swing.JMenuItem MenuItemUpdateDeleteGame;
    private javax.swing.JMenuItem MenuItemUpdateDeletePublisher;
    private javax.swing.JMenu MenuPublisher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuUser;
    // End of variables declaration//GEN-END:variables
}
