/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CMP320Project;

/**
 *
 * @author wissam
 */
public class CustomerMenu extends Menu {

     // the login user details are obtained from the Login form

    /**
     * Creates new form Menu
     * @param user
     */
    public CustomerMenu(LoginUser user) {
        luser = user;
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuItemLogout = new javax.swing.JMenuItem();
        MenuItemExit = new javax.swing.JMenuItem();
        MenuRentReturnGame = new javax.swing.JMenu();
        MenuItemRentGame = new javax.swing.JMenuItem();
        MenuItemReturnGame = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Menu");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CMP320Project/gamestore.jpg"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        MenuFile.setText("File");
        MenuFile.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        MenuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemLogout.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CMP320Project/logout.png"))); // NOI18N
        MenuItemLogout.setText("Logout");
        MenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogoutActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemLogout);

        MenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemExit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CMP320Project/close.png"))); // NOI18N
        MenuItemExit.setText("Exit");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemExit);

        jMenuBar1.add(MenuFile);

        MenuRentReturnGame.setText("Rent/Return");
        MenuRentReturnGame.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        MenuItemRentGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemRentGame.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemRentGame.setText("Rent Game");
        MenuItemRentGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemRentGameActionPerformed(evt);
            }
        });
        MenuRentReturnGame.add(MenuItemRentGame);

        MenuItemReturnGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemReturnGame.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MenuItemReturnGame.setText("Return Game");
        MenuItemReturnGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemReturnGameActionPerformed(evt);
            }
        });
        MenuRentReturnGame.add(MenuItemReturnGame);

        jMenuBar1.add(MenuRentReturnGame);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemRentGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemRentGameActionPerformed
        
        (new RentGame()).setVisible(true);
    }//GEN-LAST:event_MenuItemRentGameActionPerformed

    private void MenuItemReturnGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemReturnGameActionPerformed
        (new ReturnGame()).setVisible(true);
    }//GEN-LAST:event_MenuItemReturnGameActionPerformed

    private void MenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogoutActionPerformed
        // TODO add your handling code here:
        (new LoginForm()).setVisible(true);
        this.dispose(); // the Menu form is disposed ONLY when the currently logged in user logs out
    }//GEN-LAST:event_MenuItemLogoutActionPerformed

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuItemExitActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JMenuItem MenuItemLogout;
    private javax.swing.JMenuItem MenuItemRentGame;
    private javax.swing.JMenuItem MenuItemReturnGame;
    private javax.swing.JMenu MenuRentReturnGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
