package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ManageGameCopies extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

    public ManageGameCopies() {
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);
        
        // set all error labels to invisible
        dbCon = new myDBCon();
        getNewData();
    }

    private void getNewData() {

        try {
            rs = dbCon.executeStatement("SELECT DISTINCT store_branch_branch_ID, name FROM game_copy, store_branch WHERE store_branch_branch_ID = branch_ID ORDER BY store_branch_branch_ID ASC");
            ResultSet rs1 = dbCon.executeStatement("SELECT DISTINCT game_game_ID, title FROM game_copy, game WHERE game_game_ID = game_ID ORDER BY game_game_ID ASC");
            try {
                cmbBranchID.removeAllItems();
                cmbGameID.removeAllItems();
                // populate combo boxes              
                while (rs.next()) {     
                    cmbBranchID.addItem(rs.getInt("store_branch_branch_ID") + ": " + rs.getString("name"));
                }
                while (rs1.next()) {
                    cmbGameID.addItem(rs1.getInt("game_game_ID") + ": " + rs1.getString("title"));
                }
                rs.close();
                rs1.close();
            } catch (SQLException ex) {
                Logger.getLogger(ManageGameCopies.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected game copy.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        cmbGameID = new javax.swing.JComboBox<>();
        cmbBranchID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Game Copies");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Manage Game Copies");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Game");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Branch");

        btnUpdate.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbBranchID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbGameID, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btnUpdate)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbBranchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbGameID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnUpdate)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // checks if the input is an integer
    public boolean isInteger(String s) { 
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
  
    // validate all user entry before sending new game details to DB
    boolean isValidData(String s) {

        boolean result = true;
        if (s.trim().isEmpty() || !isInteger(s.trim()) || (Integer.parseInt(s.trim()) / 1000 > 9  || Integer.parseInt(s.trim()) < 0)) {
            javax.swing.JLabel label;
            if (s.trim().isEmpty()) {
                label = new javax.swing.JLabel("Cannot be empty.");
            } else if (!isInteger(s.trim())) {
                label = new javax.swing.JLabel("Must be a number.");
            } 
            else {
                label = new javax.swing.JLabel("Must less than 1000 and bigger than or equal to 0.");
            }
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
            result = false;
        }
        return result;
    }
                
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        try {
            if (cmbBranchID.getSelectedItem() != null && cmbGameID.getSelectedItem() != null) {
                String branch_ID = cmbBranchID.getSelectedItem().toString().split(": ")[0];
                String game_ID = cmbGameID.getSelectedItem().toString().split(": ")[0];
                String stmtSQL = "SELECT num_of_copies FROM game_copy WHERE game_game_ID = " + game_ID + " and store_branch_branch_ID = " + branch_ID;
                rs = dbCon.executeStatement(stmtSQL);
                if(rs.first()){
                    String confirm = JOptionPane.showInputDialog("There are currently " + rs.getInt("num_of_copies") + " copies. \nEnter the new amount of copies to use:");
                    if(confirm != null) {
                        if (isValidData(confirm.trim())) {  
                            // execute the update statement
                            String prepSQL = "UPDATE game_copy SET num_of_copies = " + confirm.trim() +
                                    " WHERE game_game_ID = " + game_ID + " and store_branch_branch_ID = " + branch_ID;

                            int result = dbCon.executePrepared(prepSQL);
                            if (result > 0) {                        
                                    javax.swing.JLabel label = new javax.swing.JLabel("Number of copies for branch " + branch_ID + " and game " + game_ID + " updated successfully.");
                                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);  
                                    getNewData();
                            } else {
                                // check validation errors 
                            }
                        }
                    }
                }
                
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please select the branch and game ID's");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating game." + e.getMessage());

        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbBranchID;
    private javax.swing.JComboBox<String> cmbGameID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
