package CMP320Project;

import java.awt.event.ItemListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class RentGame extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;
    String customer_ID;
            
    public RentGame() {
       
        initComponents();
            
        // center form in screen
        this.setLocationRelativeTo(null);
            
        // set all error labels to invisible
        dbCon = new myDBCon();
        
         try {    
            rs = dbCon.executeStatement("SELECT customer_ID FROM customer WHERE name LIKE '" + LoginForm.currentMenu.luser.Name + "'");
            rs.first();
            customer_ID = rs.getString("customer_ID");
            
            getNewData();
        } catch (SQLException ex) {
            Logger.getLogger(RentGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getNewData() {
        
        clearLabels();
        cmbBranchID.removeAllItems();
        cmbGameID.removeAllItems();
        try {
            rs = dbCon.executeStatement("SELECT DISTINCT game_game_ID, title FROM game_copy, game WHERE game_game_ID = game_ID AND game_game_ID NOT IN (SELECT DISTINCT game_ID FROM rent_copy WHERE customer_ID = " + customer_ID + ") ORDER BY game_game_ID ASC");
            try {
                
                // populate combo boxes
                ItemListener listener = cmbGameID.getItemListeners()[0];
                cmbGameID.removeItemListener(listener);
                while (rs.next()) {
                    cmbGameID.addItem(rs.getInt("game_game_ID") + ": " + rs.getString("title"));
                }
                rs.close();
                
                cmbGameIDItemStateChanged(null);
                cmbGameID.addItemListener(listener);
                
                
            } catch (SQLException ex) {
                Logger.getLogger(RentGame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected game copy.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void clearLabels() { //clear all labels
 
        lblBestSellerGame.setVisible(false); 
        lblTopBranch.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRent = new javax.swing.JButton();
        cmbGameID = new javax.swing.JComboBox<>();
        cmbBranchID = new javax.swing.JComboBox<>();
        lblBestSellerGame = new javax.swing.JLabel();
        lblTopBranch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rent Game");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Rent Game");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Game");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Branch");

        btnRent.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnRent.setText("Rent");
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });

        cmbGameID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbGameIDItemStateChanged(evt);
            }
        });
        cmbGameID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbGameIDPropertyChange(evt);
            }
        });

        cmbBranchID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBranchIDItemStateChanged(evt);
            }
        });
        cmbBranchID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbBranchIDPropertyChange(evt);
            }
        });

        lblBestSellerGame.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblBestSellerGame.setForeground(new java.awt.Color(255, 0, 0));
        lblBestSellerGame.setText("Best seller!");

        lblTopBranch.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblTopBranch.setForeground(new java.awt.Color(255, 0, 0));
        lblTopBranch.setText("Most popular branch!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbBranchID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbGameID, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btnRent))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBestSellerGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTopBranch, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbGameID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBestSellerGame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbBranchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTopBranch))
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(btnRent)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        // TODO add your handling code here:
        
        try {
            if (cmbBranchID.getSelectedItem() != null && cmbGameID.getSelectedItem() != null) {
                String branch_ID = cmbBranchID.getSelectedItem().toString().split(": ")[0];
                String game_ID = cmbGameID.getSelectedItem().toString().split(": ")[0];
                
                LocalDate rentDate = LocalDate.now();
                LocalDate returnDate = rentDate.plusWeeks(1);
                
                // Define a formatter for the desired format
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                // Format the current date using the formatter
                String formattedRentDate = rentDate.format(formatter);
                String formattedReturnDate = returnDate.format(formatter);
                
                String stmtSQL1 = "INSERT INTO rent_copy (customer_ID, game_ID, branch_ID, RENT_DATE, RETURN_DATE) VALUES ((SELECT customer_ID FROM customer WHERE name LIKE '" + LoginForm.currentMenu.luser.Name + "'), " + game_ID + ", " + branch_ID
                        + ", TO_DATE('" + formattedRentDate + "', 'YYYY-MM-DD'), TO_DATE('" + formattedReturnDate + "', 'YYYY-MM-DD'))";
                
                String stmtSQL2 = "UPDATE game_copy SET num_of_copies = (num_of_copies - 1) WHERE game_game_ID = " + game_ID + " AND store_branch_branch_ID = " + branch_ID;
                int result1 = dbCon.executePrepared(stmtSQL1);
                int result2 = dbCon.executePrepared(stmtSQL2);
                if(result1 > 0 && result2 > 0){
                    
                    javax.swing.JLabel label;
                    label = new javax.swing.JLabel("Rent table and number of copies for branch " + branch_ID + " and game " + game_ID + " updated successfully." 
                            + "\nThe game has been rented for 1 week! (You have until " + formattedReturnDate + " to return the game!)");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                }
                else {
                    javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Updating rents and game copies.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please select the branch and game ID's");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating game." + e.getMessage());

        }
        getNewData();
    }//GEN-LAST:event_btnRentActionPerformed

    private void cmbBranchIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbBranchIDPropertyChange
       
    }//GEN-LAST:event_cmbBranchIDPropertyChange

    private void cmbGameIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbGameIDPropertyChange
        
    }//GEN-LAST:event_cmbGameIDPropertyChange

    private void cmbGameIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbGameIDItemStateChanged
       
        lblBestSellerGame.setVisible(false);
        if(cmbGameID.getSelectedItem() != null) {
            try{
                ResultSet rs3 = dbCon.executeStatement("SELECT game_ID FROM rent_copy GROUP BY game_ID ORDER BY COUNT(*) DESC FETCH FIRST 1 ROW ONLY");
                
                if (rs3.next() && cmbGameID.getSelectedItem().toString().split(": ")[0].equalsIgnoreCase(rs3.getString("game_ID"))) {
                    lblBestSellerGame.setVisible(true);
                }
                rs3.close();
                ResultSet rs1 = dbCon.executeStatement("SELECT store_branch_branch_ID, name FROM game_copy, store_branch WHERE store_branch_branch_ID = branch_ID AND game_game_ID = " + cmbGameID.getSelectedItem().toString().split(": ")[0] + " AND num_of_copies > 0 ORDER BY store_branch_branch_ID ASC");
                cmbBranchID.removeAllItems();
                while (rs1.next()) {     
                    cmbBranchID.addItem(rs1.getInt("store_branch_branch_ID") + ": " + rs1.getString("name"));
                }
                rs1.close();
            }
            catch (SQLException e) {
                javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected available branches.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmbGameIDItemStateChanged

    private void cmbBranchIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBranchIDItemStateChanged
        
        lblTopBranch.setVisible(false);
        try {
            ResultSet rs2 = dbCon.executeStatement("SELECT branch_ID FROM rent_copy GROUP BY branch_ID ORDER BY COUNT(*) DESC FETCH FIRST 1 ROW ONLY");
            if (rs2.next() && cmbBranchID.getSelectedItem() != null && cmbBranchID.getSelectedItem().toString().split(": ")[0].equalsIgnoreCase(rs2.getString("branch_ID"))) {
                lblTopBranch.setVisible(true);
            }
            rs2.close();
        } catch (SQLException ex) {
            Logger.getLogger(RentGame.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_cmbBranchIDItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRent;
    private javax.swing.JComboBox<String> cmbBranchID;
    private javax.swing.JComboBox<String> cmbGameID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBestSellerGame;
    private javax.swing.JLabel lblTopBranch;
    // End of variables declaration//GEN-END:variables
}
