package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ReturnGame extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;
    ResultSet rsCustomerID;
    String customer_ID;

    public ReturnGame() {
        initComponents();
        dbCon = new myDBCon();
          // center form in screen 
        this.setLocationRelativeTo(null);
        try {
            rsCustomerID = dbCon.executeStatement("SELECT customer_ID FROM customer WHERE name LIKE '" + LoginForm.currentMenu.luser.Name + "'");
            rsCustomerID.first();
            customer_ID = rsCustomerID.getString("customer_ID");
            rsCustomerID.close();
        } catch (SQLException ex) {
            Logger.getLogger(ReturnGame.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        getNewData();
    }

    private void getNewData() {
        
        try {
            rs = dbCon.executeStatement("SELECT title, name, rent_date, return_date FROM rent_copy r, game g, store_branch b WHERE r.game_ID = g.game_ID AND r.branch_ID = b.branch_ID AND r.customer_ID = " + customer_ID + " ORDER BY rent_date ASC, title ASC");
            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
            
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected fields.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGameTitle = new javax.swing.JTextField();
        txtReturnDate = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        txtBranchName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRentDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Return Game");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Return Game");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Game Title");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Branch Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Return Date");

        txtGameTitle.setEditable(false);
        txtGameTitle.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtGameTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGameTitleActionPerformed(evt);
            }
        });

        txtReturnDate.setEditable(false);
        txtReturnDate.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtReturnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReturnDateActionPerformed(evt);
            }
        });

        btnReturn.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        txtBranchName.setEditable(false);
        txtBranchName.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtBranchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Rent Date");

        txtRentDate.setEditable(false);
        txtRentDate.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtRentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRentDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGameTitle)
                            .addComponent(txtBranchName)
                            .addComponent(txtRentDate)
                            .addComponent(txtReturnDate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(btnPrevious)
                                .addGap(18, 18, 18)
                                .addComponent(btnReturn)
                                .addGap(18, 18, 18)
                                .addComponent(btnNext)))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateFields() {
        
        try {
            if (!rs.isBeforeFirst() && !rs.isAfterLast()) { // Check if there is a next row
                txtGameTitle.setText(rs.getString("title"));
                txtBranchName.setText(rs.getString("name"));
                txtRentDate.setText(rs.getString("rent_date").substring(0, 10));
                txtReturnDate.setText(rs.getString("return_date").substring(0, 10));
                EnableDisableButtons(); // Enable/disable navigation buttons based on the current position
            } else {
                // No rows in the result set, clear all fields
                txtGameTitle.setText("");
                txtBranchName.setText("");
                txtRentDate.setText("");
                txtReturnDate.setText("");
                // Disable navigation buttons since there are no records to navigate
                btnPrevious.setEnabled(false);
                btnNext.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReturnGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MoveNext() { // selecting the next customer and autofilling the textboxes with the customer values
        try {
            // TODO add your handling code here:
            if (!rs.isLast()) {
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReturnGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void MovePrevious() { // selecting the prev customer and autofilling the textboxes with the customer values
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReturnGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReturnGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        try {
            if (!rs.isBeforeFirst()) {
                // search for active rents with that customer
                String prepSQL1 = "UPDATE game_copy SET num_of_copies = (num_of_copies + 1) "
                            + "WHERE game_game_ID = (SELECT game_ID from game WHERE title LIKE '" + txtGameTitle.getText() + "') "
                            + "AND store_branch_branch_ID = (SELECT branch_ID from store_branch "
                            + "WHERE name LIKE '" + txtBranchName.getText() + "')";
                String prepSQL2 = "DELETE FROM rent_copy "
                        + "WHERE game_ID = (SELECT game_ID from game WHERE title LIKE '" + txtGameTitle.getText() + "') "
                                + "AND branch_ID = (SELECT branch_ID from store_branch "
                                + "WHERE name LIKE '" + txtBranchName.getText() + "')";
                
                ResultSet newRS = dbCon.executeStatement("SELECT rental_price FROM game WHERE title LIKE '" + txtGameTitle.getText() + "'");
                // ask the user if they want to continue
                newRS.first();
                double value = newRS.getDouble("rental_price");

                LocalDate currentDate = LocalDate.now();
                // Convert the string date to LocalDate
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDate providedDate = LocalDate.parse(txtReturnDate.getText(), formatter);

                // Compare the dates
                if (currentDate.isAfter(providedDate)) {
                    javax.swing.JLabel label = new javax.swing.JLabel("You're returning the game late, a late fee of 50 AED will apply.");
                    value += 50;
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                }
                String confirm = JOptionPane.showInputDialog("The amount to be paid is " + value + " AED. Type \"yes\" to confirm.");
                confirm += " ";
                if(confirm.equalsIgnoreCase("yes ")) {
                    int result1 = dbCon.executePrepared(prepSQL1);
                    int result2 = dbCon.executePrepared(prepSQL2);
                    if (result1 > 0 && result2 > 0) {
                        javax.swing.JLabel label = new javax.swing.JLabel("Game returned successfully.\nThank you for shopping with us.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                
                else{
                    JOptionPane.showMessageDialog(null, "Error returning game.");
                }
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error returning game with SQL.");
        }
        getNewData();
    }//GEN-LAST:event_btnReturnActionPerformed

     
    private void txtReturnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReturnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReturnDateActionPerformed

    private void txtGameTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGameTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGameTitleActionPerformed

    private void txtBranchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchNameActionPerformed

    private void txtRentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtBranchName;
    private javax.swing.JTextField txtGameTitle;
    private javax.swing.JTextField txtRentDate;
    private javax.swing.JTextField txtReturnDate;
    // End of variables declaration//GEN-END:variables
}
