package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class UpdateDeleteDeveloper extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

    public UpdateDeleteDeveloper() {
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);
        
        // set all error labels to invisible
        lblDeveloperIDError.setVisible(false);
        lblDeveloperNameError.setVisible(false);
        lblDeveloperEmailError.setVisible(false);
        dbCon = new myDBCon();
        getNewData();
    }

    private void getNewData() {

        try {
            rs = dbCon.executeStatement("SELECT * FROM developer ORDER BY developer_ID ASC");
            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
            
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected deptno.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDeveloperID = new javax.swing.JTextField();
        txtDeveloperEmail = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        lblDeveloperIDError = new javax.swing.JLabel();
        lblDeveloperNameError = new javax.swing.JLabel();
        lblDeveloperEmailError = new javax.swing.JLabel();
        txtDeveloperName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update/Delete Developer");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Developer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Developer_ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Developer Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Email");

        txtDeveloperID.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtDeveloperID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeveloperIDActionPerformed(evt);
            }
        });

        txtDeveloperEmail.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtDeveloperEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeveloperEmailActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        lblDeveloperIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDeveloperIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblDeveloperIDError.setText("error label");

        lblDeveloperNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDeveloperNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblDeveloperNameError.setText("error label");

        lblDeveloperEmailError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDeveloperEmailError.setForeground(new java.awt.Color(255, 0, 0));
        lblDeveloperEmailError.setText("error label");
        lblDeveloperEmailError.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblDeveloperEmailErrorComponentShown(evt);
            }
        });

        txtDeveloperName.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtDeveloperName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeveloperNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeveloperEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(txtDeveloperID)
                            .addComponent(txtDeveloperName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeveloperIDError, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDeveloperNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDeveloperEmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel1)))
                        .addGap(0, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDeveloperIDError)
                    .addComponent(txtDeveloperID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDeveloperNameError)
                    .addComponent(txtDeveloperName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDeveloperEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeveloperEmailError))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateFields() {
        try {
            txtDeveloperID.setText(rs.getString("developer_ID"));
            txtDeveloperName.setText(rs.getString("name"));
            txtDeveloperEmail.setText(rs.getString("email"));
            // autofill the text boxes with the values retrieved from the database
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteDeveloper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MoveNext() { // selecting the next department and autofilling the textboxes with the dept values
        try {
            // TODO add your handling code here:
            if (!rs.isLast()) {
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteDeveloper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void MovePrevious() { // selecting the prev department and autofilling the textboxes with the dept values
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteDeveloper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteDeveloper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            // search for games with that developer
            rs = dbCon.executeStatement("select * from develops where developer_ID = " + txtDeveloperID.getText().trim()) ;
            rs.beforeFirst();
            if(rs.next()) {
                // if any developer still has a registered game, you cannot delete them
                JOptionPane.showMessageDialog(null, "Cannot delete a developer that has registered games.");
            }
            else{
                // ask the user if they want to continue
                String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
                confirm += " ";
                if(confirm.equalsIgnoreCase("yes ")) {
                    // delete the dept
                    String prepSQL = "DELETE developer WHERE developer_ID = " + txtDeveloperID.getText().trim();
                    int result = dbCon.executePrepared(prepSQL);
                    if (result > 0) {
                        javax.swing.JLabel label = new javax.swing.JLabel("Developer ID " + txtDeveloperID.getText().trim() + " deleted successfully.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        getNewData();
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting developer.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    void clearErrorLabels() { //clear all error labels
        lblDeveloperIDError.setText("");
        lblDeveloperIDError.setVisible(false);
        lblDeveloperNameError.setText("");
        lblDeveloperNameError.setVisible(false);
        lblDeveloperEmailError.setText("");
        lblDeveloperEmailError.setVisible(false);
    }

    // checks if the input is an integer
    public boolean isInteger(String s) { 
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtDeveloperID.getText().trim().isEmpty() || !isInteger(txtDeveloperID.getText().trim()) || (Integer.parseInt(txtDeveloperID.getText().trim()) / 1000 > 9)) {
            if (txtDeveloperID.getText().trim().isEmpty()) {
                lblDeveloperIDError.setText("Cannot be empty.");
            } else if (!isInteger(txtDeveloperID.getText().trim())) {
                lblDeveloperIDError.setText("Must be integer.");
            }
            else{
                lblDeveloperIDError.setText("Must be 4 digits at most.");
            }
            lblDeveloperIDError.setVisible(true);
            result = false;
        }

        if (txtDeveloperName.getText().trim().isEmpty() || (txtDeveloperName.getText().trim().length() > 25)) {
            if (txtDeveloperName.getText().trim().isEmpty()) {
                lblDeveloperNameError.setText("Cannot be empty.");
            } else if ((txtDeveloperName.getText().trim().length() > 10)) {
                lblDeveloperNameError.setText("Must be < 26 chars.");
            }
            lblDeveloperNameError.setVisible(true);
            result = false;
        }

        if (txtDeveloperEmail.getText().trim().isEmpty() || (txtDeveloperEmail.getText().trim().length() > 25)) {
            if (txtDeveloperEmail.getText().trim().isEmpty()) {
                lblDeveloperEmailError.setText("Cannot be empty.");
            } else {
                lblDeveloperEmailError.setText("Must be < 26 chars.");
            }
            lblDeveloperEmailError.setVisible(true);
            result = false;
        }

        return result;
    }
    
    private boolean isDuplicate(String developer_ID){
        try {
            // if the user changes the developer_ID (the developer_ID in the text box is not the same as the developer_ID that was shown to the user)
            if(!(developer_ID.equals(rs.getString("developer_ID")))){
                //check if the developer_ID exists in the DB
                String stmtSQL = "SELECT developer_ID FROM developer WHERE developer_ID = " + developer_ID;
                ResultSet newRS;
                newRS = dbCon.executeStatement(stmtSQL);
                // isBeforeFirst() returns false if there are no data in the resultset
                return newRS.isBeforeFirst();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteLoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return false;
    }                
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        try {
            if (isValidData() && !isDuplicate(txtDeveloperID.getText().trim())) { // if data was valid and developer_ID did not change to a new duplicate value
                String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
                confirm += " "; // to ensure confirm is never null
                if(confirm.equalsIgnoreCase("yes ")) {
                    // execute the update statement
                    String prepSQL = "UPDATE developer SET name = " + 
                        "'" + txtDeveloperName.getText().trim().toUpperCase() + 
                        "', email = '" + txtDeveloperEmail.getText().trim().toUpperCase() +
                        "', developer_ID = " + txtDeveloperID.getText().trim() + 
                        " WHERE developer_ID = " + rs.getInt("developer_ID");
                            //the old developer_ID, not the one that the user types in
                            //the ResultSet rs contains the info of the developer_ID before the update is executed
                    
                    int result = dbCon.executePrepared(prepSQL);
                    if (result > 0) {
                        ResultSet rs2 = dbCon.executeStatement("select * from develops where developer_ID = " + rs.getInt("developer_ID"));
                        if(rs2.isBeforeFirst()) { // if the developer had any games we change their respective developer_ID
                            
                            //update the developer_ID of all the games which developer got updated
                            String prepSQL1 = "UPDATE develops SET developer_ID = " 
                                // set as the new value
                                + txtDeveloperID.getText().trim()
                                // search for the old value
                                + " WHERE developer_ID = " + rs.getInt("developer_ID");
                            int result1 = dbCon.executePrepared(prepSQL1);
                            if(result1 > 0){
                                // successful update
                                javax.swing.JLabel label = new javax.swing.JLabel("Developer ID " + txtDeveloperID.getText() + " updated successfully for all the games.");
                                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                                getNewData();
                            }
                        }
                        else {
                            javax.swing.JLabel label = new javax.swing.JLabel("Developer ID " + txtDeveloperID.getText() + " updated successfully.");
                            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                            JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                            getNewData();
                        }
                        
                    } else {
                        // check validation errors 
                    }
                }
                else{
                    
                }
//                prepStatement.close();
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating developer." + e.getMessage());

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtDeveloperEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeveloperEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeveloperEmailActionPerformed

    private void txtDeveloperIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeveloperIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeveloperIDActionPerformed

    private void txtDeveloperNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeveloperNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeveloperNameActionPerformed

    private void lblDeveloperEmailErrorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblDeveloperEmailErrorComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDeveloperEmailErrorComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDeveloperEmailError;
    private javax.swing.JLabel lblDeveloperIDError;
    private javax.swing.JLabel lblDeveloperNameError;
    private javax.swing.JTextField txtDeveloperEmail;
    private javax.swing.JTextField txtDeveloperID;
    private javax.swing.JTextField txtDeveloperName;
    // End of variables declaration//GEN-END:variables
}
