package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class UpdateDeleteBranch extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

    public UpdateDeleteBranch() {
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);
        
        // set all error labels to invisible
        clearErrorLabels();
        dbCon = new myDBCon();
        getNewData();
    }

    private void getNewData() {

        try {
            rs = dbCon.executeStatement("SELECT branch_ID, name, country, city, street FROM store_branch ORDER BY branch_ID ASC");
            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
            
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected branch_ID.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBranchID = new javax.swing.JTextField();
        txtBranchCountry = new javax.swing.JTextField();
        btnUpdateBranch = new javax.swing.JButton();
        btnDeleteBranch = new javax.swing.JButton();
        btnNextBranch = new javax.swing.JButton();
        btnPreviousBranch = new javax.swing.JButton();
        lblBranchIDError = new javax.swing.JLabel();
        lblBranchNameError = new javax.swing.JLabel();
        lblBranchCountryError = new javax.swing.JLabel();
        txtBranchName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UpdateDeleteBranchID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBranchStreet = new javax.swing.JTextField();
        txtBranchCity = new javax.swing.JTextField();
        lblBranchCityError = new javax.swing.JLabel();
        lblBranchStreetError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update/Delete Branch");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Branch");

        txtBranchID.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtBranchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchIDActionPerformed(evt);
            }
        });

        txtBranchCountry.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtBranchCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchCountryActionPerformed(evt);
            }
        });

        btnUpdateBranch.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdateBranch.setText("Update");
        btnUpdateBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBranchActionPerformed(evt);
            }
        });

        btnDeleteBranch.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDeleteBranch.setText("Delete");
        btnDeleteBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBranchActionPerformed(evt);
            }
        });

        btnNextBranch.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNextBranch.setText("Next >>");
        btnNextBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextBranchActionPerformed(evt);
            }
        });

        btnPreviousBranch.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPreviousBranch.setText("<< Previous");
        btnPreviousBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousBranchActionPerformed(evt);
            }
        });

        lblBranchIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblBranchIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblBranchIDError.setText("error label");

        lblBranchNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblBranchNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblBranchNameError.setText("error label");

        lblBranchCountryError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblBranchCountryError.setForeground(new java.awt.Color(255, 0, 0));
        lblBranchCountryError.setText("error label");
        lblBranchCountryError.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblBranchCountryErrorComponentShown(evt);
            }
        });

        txtBranchName.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtBranchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchNameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("COUNTRY");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("STREET");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("BRANCH NAME");

        UpdateDeleteBranchID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UpdateDeleteBranchID.setText("BRANCH_ID");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("CITY");

        txtBranchStreet.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtBranchStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchStreetActionPerformed(evt);
            }
        });

        txtBranchCity.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtBranchCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchCityActionPerformed(evt);
            }
        });

        lblBranchCityError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblBranchCityError.setForeground(new java.awt.Color(255, 0, 0));
        lblBranchCityError.setText("error label");
        lblBranchCityError.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblBranchCityErrorComponentShown(evt);
            }
        });

        lblBranchStreetError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblBranchStreetError.setForeground(new java.awt.Color(255, 0, 0));
        lblBranchStreetError.setText("error label");
        lblBranchStreetError.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblBranchStreetErrorComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateDeleteBranchID)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtBranchID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBranchCountry, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtBranchStreet, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBranchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBranchNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBranchIDError, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(lblBranchCountryError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBranchCityError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBranchStreetError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnPreviousBranch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateBranch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteBranch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextBranch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateDeleteBranchID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblBranchNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(lblBranchCountryError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lblBranchCityError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lblBranchStreetError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateBranch)
                    .addComponent(btnDeleteBranch)
                    .addComponent(btnNextBranch)
                    .addComponent(btnPreviousBranch))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateFields() {
        try {
            txtBranchID.setText(rs.getString("branch_ID"));
            txtBranchName.setText(rs.getString("name"));
            txtBranchCountry.setText(rs.getString("country"));
            txtBranchCity.setText(rs.getString("city"));
            txtBranchStreet.setText(rs.getString("street"));
            // autofill the text boxes with the values retrieved from the database
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteBranch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MoveNext() { // selecting the next department and autofilling the textboxes with the dept values
        try {
            // TODO add your handling code here:
            if (!rs.isLast()) {
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteBranch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnNextBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextBranchActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextBranchActionPerformed

    private void MovePrevious() { // selecting the prev department and autofilling the textboxes with the dept values
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteBranch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            if (rs.isFirst()) {
                btnPreviousBranch.setEnabled(false);
            } else {
                btnPreviousBranch.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNextBranch.setEnabled(false);
            } else {
                btnNextBranch.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteBranch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnPreviousBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousBranchActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousBranchActionPerformed

    private void btnDeleteBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBranchActionPerformed
        // TODO add your handling code here:
        // ask the user if they want to continue
        String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
        confirm += " ";
        if(confirm.equalsIgnoreCase("yes ")) {
            try {
                
                ResultSet rents = dbCon.executeStatement("SELECT * FROM rent_copy where branch_ID = " + txtBranchID.getText().trim());
                if (!rents.next()) {
                    String prepSQL = "DELETE game_copy WHERE store_branch_branch_ID = " + txtBranchID.getText().trim();
                    int result = dbCon.executePrepared(prepSQL);
                    if (result > 0) {
                        prepSQL = "DELETE store_branch WHERE branch_ID = " + txtBranchID.getText().trim();
                        result = dbCon.executePrepared(prepSQL);
                        if (result > 0) {
                            javax.swing.JLabel label = new javax.swing.JLabel("Branch ID " + txtBranchID.getText().trim() + " deleted successfully.");
                            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                            JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                            getNewData();
                        }
                    }
                }
                else {
                    JOptionPane.showMessageDialog(null, "Cannot delete a branch that currently has rented games");
                }
            } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting branch.");
            }
        }
    }//GEN-LAST:event_btnDeleteBranchActionPerformed

    private void clearErrorLabels() { //clear all error labels
                
        lblBranchIDError.setText("");
        lblBranchIDError.setVisible(false);
        lblBranchNameError.setText("");
        lblBranchNameError.setVisible(false);
        lblBranchCountryError.setText("");
        lblBranchCountryError.setVisible(false);
        lblBranchCityError.setText("");
        lblBranchCityError.setVisible(false);
        lblBranchStreetError.setText("");
        lblBranchStreetError.setVisible(false);
    }

    // checks if the input is an integer
    public boolean isInteger(String s) { 
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

   // validate all user entry before sending new branch details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtBranchID.getText().trim().isEmpty() || !isInteger(txtBranchID.getText().trim()) || (Integer.parseInt(txtBranchID.getText().trim())/10 > 9)) {
            if (txtBranchID.getText().trim().isEmpty()) {
                lblBranchIDError.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(txtBranchID.getText().trim())) {
                lblBranchIDError.setText("Invalid. Must be integer.");
            }
            else {
                lblBranchIDError.setText("Invalid. Must be 2 digits.");
            }
            lblBranchIDError.setVisible(true);
            result = false;
        }

        if (txtBranchName.getText().trim().isEmpty() || (txtBranchName.getText().trim().length() > 25)) {
            if (txtBranchName.getText().trim().isEmpty()) {
                lblBranchNameError.setText("Invalid. Cannot be empty.");
            } else if ((txtBranchName.getText().trim().length() > 14)) {
                lblBranchNameError.setText("Invalid. Must be < 26 chars.");
            }
            lblBranchNameError.setVisible(true);
            result = false;
        }

        if (txtBranchCountry.getText().trim().isEmpty() || (txtBranchCountry.getText().trim().length() > 25)) {
            if (txtBranchCountry.getText().trim().isEmpty()) {
                lblBranchCountryError.setText("Invalid. Cannot be empty.");
            } else if (txtBranchCountry.getText().trim().length() > 13) {
                lblBranchCountryError.setText("Invalid. Must be < 26 chars.");
            }
            lblBranchCountryError.setVisible(true);
            result = false;
        }
        
        if (txtBranchCity.getText().trim().isEmpty() || (txtBranchCity.getText().trim().length() > 25)) {
            if (txtBranchCity.getText().trim().isEmpty()) {
                lblBranchCityError.setText("Invalid. Cannot be empty.");
            } else if (txtBranchCity.getText().trim().length() > 13) {
                lblBranchCityError.setText("Invalid. Must be < 26 chars.");
            }
            lblBranchCityError.setVisible(true);
            result = false;
        }
        if (txtBranchStreet.getText().trim().isEmpty() || (txtBranchStreet.getText().trim().length() > 25)) {
            if (txtBranchStreet.getText().trim().isEmpty()) {
                lblBranchStreetError.setText("Invalid. Cannot be empty.");
            } else if (txtBranchStreet.getText().trim().length() > 13) {
                lblBranchStreetError.setText("Invalid. Must be < 26 chars.");
            }
            lblBranchStreetError.setVisible(true);
            result = false;
        }

        return result;
    }
    
    private boolean isDuplicate(String deptno){
        try {
            // if the user changes the branch_ID (the branch_ID in the text box is not the same as the branch_ID that was shown to the user)
            if(!(deptno.equals(rs.getString("branch_ID")))){
                //check if the branch_ID exists in the DB
                String stmtSQL = "SELECT branch_ID FROM store_branch WHERE branch_ID = " + deptno;
                ResultSet newRS;
                newRS = dbCon.executeStatement(stmtSQL);
                // isBeforeFirst() returns false if there are no data in the resultset
                return newRS.isBeforeFirst();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteLoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return false;
    }                
    
    private void btnUpdateBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBranchActionPerformed
        // TODO add your handling code here:

        try {
            if (isValidData() && !isDuplicate(txtBranchID.getText().trim())) { // if data was valid and deptno did not change to a new duplicate value
                String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
                confirm += " "; // to ensure confirm is never null
                if(confirm.equalsIgnoreCase("yes ")) {
                    dbCon.executeStatement("ALTER TABLE game_copy DISABLE CONSTRAINT Game_copy_Store_branch_FK");
                    // execute the update statement
                    String prepSQL = "UPDATE store_branch SET branch_ID = " + txtBranchID.getText().trim()
                            + ", name = '" + txtBranchName.getText().trim().toUpperCase() + 
                            "', country = '" + txtBranchCountry.getText().trim().toUpperCase() +
                            "', city = '" + txtBranchCity.getText().trim().toUpperCase() +
                            "', street = '" + txtBranchStreet.getText().trim().toUpperCase() +
                            "' WHERE branch_ID = " + rs.getInt("branch_ID");
                            //the old branch_ID, not the one that the user types in
                            //the ResultSet rs contains the info of the store_branch before the update is executed
                    
                    int result = dbCon.executePrepared(prepSQL);
                    if (result > 0) {
                        ResultSet rs2 = dbCon.executeStatement("select * from game_copy where store_branch_branch_id = " + rs.getInt("branch_ID"));
                        if(rs2.isBeforeFirst()) { 
                               
                            prepSQL = "UPDATE game_copy SET store_branch_branch_id = " + txtBranchID.getText().trim() + " WHERE store_branch_branch_id = " + rs.getInt("branch_ID");
                            result = dbCon.executePrepared(prepSQL);
                        }
                        
                        if (result > 0) {
                            rs2 = dbCon.executeStatement("select * from rent_copy where branch_id = " + rs.getInt("branch_ID"));
                            if(rs2.isBeforeFirst()) { 

                                prepSQL = "UPDATE rent_copy SET branch_id = " + txtBranchID.getText().trim() + " WHERE branch_id = " + rs.getInt("branch_ID");
                                result = dbCon.executePrepared(prepSQL);
                                if(result > 0){
                                    // successful update
                                    javax.swing.JLabel label = new javax.swing.JLabel("Branch ID " + txtBranchID.getText() + " updated successfully.");
                                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                                    getNewData();                        
                                }
                            }                        
                        } 
                    }
                    dbCon.executeStatement("ALTER TABLE game_copy ENABLE CONSTRAINT Game_copy_Store_branch_FK");
                }
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating branch." + e.getMessage());

        }
    }//GEN-LAST:event_btnUpdateBranchActionPerformed

    private void txtBranchCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchCountryActionPerformed

    private void txtBranchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchIDActionPerformed

    private void txtBranchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchNameActionPerformed

    private void lblBranchCountryErrorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblBranchCountryErrorComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBranchCountryErrorComponentShown

    private void txtBranchStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchStreetActionPerformed

    private void txtBranchCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchCityActionPerformed

    private void lblBranchCityErrorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblBranchCityErrorComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBranchCityErrorComponentShown

    private void lblBranchStreetErrorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblBranchStreetErrorComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBranchStreetErrorComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UpdateDeleteBranchID;
    private javax.swing.JButton btnDeleteBranch;
    private javax.swing.JButton btnNextBranch;
    private javax.swing.JButton btnPreviousBranch;
    private javax.swing.JButton btnUpdateBranch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBranchCityError;
    private javax.swing.JLabel lblBranchCountryError;
    private javax.swing.JLabel lblBranchIDError;
    private javax.swing.JLabel lblBranchNameError;
    private javax.swing.JLabel lblBranchStreetError;
    private javax.swing.JTextField txtBranchCity;
    private javax.swing.JTextField txtBranchCountry;
    private javax.swing.JTextField txtBranchID;
    private javax.swing.JTextField txtBranchName;
    private javax.swing.JTextField txtBranchStreet;
    // End of variables declaration//GEN-END:variables
}
