package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class UpdateDeleteCustomer extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

    public UpdateDeleteCustomer() {
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);
        
        // set all error labels to invisible
        clearErrorLabels();
        dbCon = new myDBCon();
        getNewData();
    }

    private void getNewData() {

        try {
            rs = dbCon.executeStatement("SELECT * FROM customer ORDER BY customer_ID ASC");
            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
            
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected deptno.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        txtCustomerEmail = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        lblCustomerIDError = new javax.swing.JLabel();
        lblCustomerNameError = new javax.swing.JLabel();
        lblCustomerEmailError = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerPhoneNumber = new javax.swing.JTextField();
        lblCustomerPhoneNumberError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update/Delete Customer");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Customer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Customer_ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Email");

        txtCustomerID.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIDActionPerformed(evt);
            }
        });

        txtCustomerEmail.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtCustomerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerEmailActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        lblCustomerIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCustomerIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblCustomerIDError.setText("error label");

        lblCustomerNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCustomerNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblCustomerNameError.setText("error label");

        lblCustomerEmailError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCustomerEmailError.setForeground(new java.awt.Color(255, 0, 0));
        lblCustomerEmailError.setText("error label");
        lblCustomerEmailError.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblCustomerEmailErrorComponentShown(evt);
            }
        });

        txtCustomerName.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Phone Number");

        txtCustomerPhoneNumber.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        txtCustomerPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerPhoneNumberActionPerformed(evt);
            }
        });

        lblCustomerPhoneNumberError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCustomerPhoneNumberError.setForeground(new java.awt.Color(255, 0, 0));
        lblCustomerPhoneNumberError.setText("error label");
        lblCustomerPhoneNumberError.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblCustomerPhoneNumberErrorComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCustomerEmail)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtCustomerPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCustomerNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCustomerIDError, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(lblCustomerPhoneNumberError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCustomerEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCustomerIDError)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCustomerNameError)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerPhoneNumberError))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCustomerEmailError)
                        .addComponent(txtCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateFields() {
        try {
            txtCustomerID.setText(rs.getString("customer_ID"));
            txtCustomerName.setText(rs.getString("name"));
            txtCustomerPhoneNumber.setText(rs.getString("phone_number"));
            txtCustomerEmail.setText(rs.getString("email"));
            // autofill the text boxes with the values retrieved from the database
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MoveNext() { // selecting the next customer and autofilling the textboxes with the customer values
        try {
            // TODO add your handling code here:
            if (!rs.isLast()) {
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void MovePrevious() { // selecting the prev customer and autofilling the textboxes with the customer values
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            // search for active rents with that customer
            rs = dbCon.executeStatement("select * from rent_copy where customer_ID = " + txtCustomerID.getText().trim()) ;
            rs.beforeFirst();
            if(rs.next()) {
                // if any customer still has a rented game, you cannot delete them
                JOptionPane.showMessageDialog(null, "Cannot delete a customer that hasn't returned their rented game.");
            }
            else{
                // ask the user if they want to continue
                String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
                confirm += " ";
                if(confirm.equalsIgnoreCase("yes ")) {
                    // delete the customer
                    String prepSQL = "DELETE customer WHERE customer_ID = " + txtCustomerID.getText().trim();
                    int result = dbCon.executePrepared(prepSQL);
                    if (result > 0) {
                        javax.swing.JLabel label = new javax.swing.JLabel("Customer ID " + txtCustomerID.getText().trim() + " deleted successfully.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        getNewData();
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting customer.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    void clearErrorLabels() { //clear all error labels
        lblCustomerIDError.setText("");
        lblCustomerIDError.setVisible(false);
        lblCustomerNameError.setText("");
        lblCustomerNameError.setVisible(false);
        lblCustomerPhoneNumberError.setText("");
        lblCustomerPhoneNumberError.setVisible(false);
        lblCustomerEmailError.setText("");
        lblCustomerEmailError.setVisible(false);
    }

    // checks if the input is an integer
    public boolean isInteger(String s) { 
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtCustomerID.getText().trim().isEmpty() || !isInteger(txtCustomerID.getText().trim()) || (Integer.parseInt(txtCustomerID.getText().trim()) / 1000 > 9)) {
            if (txtCustomerID.getText().trim().isEmpty()) {
                lblCustomerIDError.setText("Cannot be empty.");
            } else if (!isInteger(txtCustomerID.getText().trim())) {
                lblCustomerIDError.setText("Must be integer.");
            }
            else{
                lblCustomerIDError.setText("Must be 4 digits at most.");
            }
            lblCustomerIDError.setVisible(true);
            result = false;
        }

        if (txtCustomerName.getText().trim().isEmpty() || (txtCustomerName.getText().trim().length() > 25)) {
            if (txtCustomerName.getText().trim().isEmpty()) {
                lblCustomerNameError.setText("Cannot be empty.");
            } else if ((txtCustomerName.getText().trim().length() > 10)) {
                lblCustomerNameError.setText("Must be < 26 chars.");
            }
            lblCustomerNameError.setVisible(true);
            result = false;
        }

        if (txtCustomerPhoneNumber.getText().trim().isEmpty() || !Pattern.matches("^\\+\\d{3}-\\d{2}-\\d{7}$", txtCustomerPhoneNumber.getText().trim())) {
            if (txtCustomerPhoneNumber.getText().trim().isEmpty()) {
                lblCustomerPhoneNumberError.setText("Cannot be empty.");
            } else {
                lblCustomerPhoneNumberError.setText("Phone number must be in the specified format.");
            }
            lblCustomerPhoneNumberError.setVisible(true);
            result = false;
        }
        
        if (txtCustomerEmail.getText().trim().isEmpty() || (txtCustomerEmail.getText().trim().length() > 25)) {
            if (txtCustomerEmail.getText().trim().isEmpty()) {
                lblCustomerEmailError.setText("Cannot be empty.");
            } else if ((txtCustomerEmail.getText().trim().length() > 10)) {
                lblCustomerEmailError.setText("Must be < 26 chars.");
            }
            lblCustomerEmailError.setVisible(true);
            result = false;
        }

        return result;
    }
    
    private boolean isDuplicate(String customer_ID){
        try {
            // if the user changes the customer_ID (the customer_ID in the text box is not the same as the customer_ID that was shown to the user)
            if(!(customer_ID.equals(rs.getString("customer_ID")))){
                //check if the customer_ID exists in the DB
                String stmtSQL = "SELECT customer_ID FROM customer WHERE customer_ID = " + customer_ID;
                ResultSet newRS;
                newRS = dbCon.executeStatement(stmtSQL);
                // isBeforeFirst() returns false if there are no data in the resultset
                return newRS.isBeforeFirst();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteLoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return false;
    }                
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        try {
            if (isValidData() && !isDuplicate(txtCustomerID.getText().trim())) { // if data was valid and customer_ID did not change to a new duplicate value
                String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
                confirm += " "; // to ensure confirm is never null
                if(confirm.equalsIgnoreCase("yes ")) {
                    // execute the update statement
                    String prepSQL = "UPDATE customer SET name = " + 
                        "'" + txtCustomerName.getText().trim().toUpperCase() +
                        "', phone_number = '" + txtCustomerPhoneNumber.getText().trim() +
                        "', email = '" + txtCustomerEmail.getText().trim() +
                        "', customer_ID = " + txtCustomerID.getText().trim() + 
                        " WHERE customer_ID = " + rs.getInt("customer_ID");
                            //the old customer_ID, not the one that the user types in
                            //the ResultSet rs contains the info of the customer_ID before the update is executed
                    
                    int result = dbCon.executePrepared(prepSQL);
                    if (result > 0) {
                        
                        prepSQL = "UPDATE loginusers SET name = " + 
                           "'" + txtCustomerName.getText().trim().toUpperCase() +
                           "' WHERE name LIKE '" + rs.getString("name") + "'";                                

                        result = dbCon.executePrepared(prepSQL);
                        
                        if (result > 0) {
                            ResultSet rs2 = dbCon.executeStatement("select * from rent_copy where customer_ID = " + rs.getInt("customer_ID"));
                            if(rs2.isBeforeFirst()) { // if the customer had any games rented we change their respective customer_ID

                                //update the customer_ID of all the rents which customer got updated
                                String prepSQL1 = "UPDATE rent_copy SET customer_ID = " 
                                    // set as the new value
                                    + txtCustomerID.getText().trim()
                                    // search for the old value
                                    + " WHERE customer_ID = " + rs.getInt("customer_ID");
                                int result1 = dbCon.executePrepared(prepSQL1);
                                if(result1 > 0){
                                    // successful update
                                    javax.swing.JLabel label = new javax.swing.JLabel("Customer ID " + txtCustomerID.getText() + " updated successfully for all the rents.");
                                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                                    getNewData();
                                }
                            }
                            else {
                                javax.swing.JLabel label = new javax.swing.JLabel("Customer ID " + txtCustomerID.getText() + " updated successfully.");
                                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                                getNewData();
                            }
                        }
                        else {
                           javax.swing.JLabel label = new javax.swing.JLabel("Error updating loginuser names");
                           label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                           JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE); 
                        }
                        
                    } else {
                        javax.swing.JLabel label = new javax.swing.JLabel("Error updating customer");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE); 
                    }
                }
                else{
                    
                }
//                prepStatement.close();
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating customer." + e.getMessage());

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtCustomerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerEmailActionPerformed

    private void txtCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIDActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void lblCustomerEmailErrorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblCustomerEmailErrorComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCustomerEmailErrorComponentShown

    private void txtCustomerPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerPhoneNumberActionPerformed

    private void lblCustomerPhoneNumberErrorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblCustomerPhoneNumberErrorComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCustomerPhoneNumberErrorComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCustomerEmailError;
    private javax.swing.JLabel lblCustomerIDError;
    private javax.swing.JLabel lblCustomerNameError;
    private javax.swing.JLabel lblCustomerPhoneNumberError;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
