package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class UpdateDeletePublisher extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

    public UpdateDeletePublisher() {
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);
        
        // set all error labels to invisible
        clearErrorLabels();
        dbCon = new myDBCon();
        getNewData();
    }

    private void getNewData() {

        try {
            rs = dbCon.executeStatement("SELECT * FROM publisher ORDER BY name ASC");
            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
            
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected deptno.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPublisherEmail = new javax.swing.JTextField();
        lblPublisherEmailError = new javax.swing.JLabel();
        lblPublisherPhoneNumberError = new javax.swing.JLabel();
        txtPublisherPhoneNumber = new javax.swing.JTextField();
        txtPublisherStreet = new javax.swing.JTextField();
        lblPublisherStreetError = new javax.swing.JLabel();
        txtPublisherCity = new javax.swing.JTextField();
        lblPublisherCityError = new javax.swing.JLabel();
        txtPublisherCountry = new javax.swing.JTextField();
        lblPublisherCountryError = new javax.swing.JLabel();
        txtPublisherName = new javax.swing.JTextField();
        lblPublisherNameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update/Delete Publisher");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Publisher");

        btnUpdate.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Publisher Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Country");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("City");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Street");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Phone Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Email");

        txtPublisherEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPublisherEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPublisherEmailActionPerformed(evt);
            }
        });

        lblPublisherEmailError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherEmailError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherEmailError.setText("error label");

        lblPublisherPhoneNumberError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherPhoneNumberError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherPhoneNumberError.setText("error label");

        txtPublisherPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPublisherPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPublisherPhoneNumberActionPerformed(evt);
            }
        });

        txtPublisherStreet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblPublisherStreetError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherStreetError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherStreetError.setText("error label");

        txtPublisherCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblPublisherCityError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherCityError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherCityError.setText("error label");

        txtPublisherCountry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblPublisherCountryError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherCountryError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherCountryError.setText("error label");

        txtPublisherName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblPublisherNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPublisherNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisherNameError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPublisherCountry, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPublisherStreet, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPublisherCity)
                                    .addComponent(txtPublisherName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPublisherNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPublisherCountryError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPublisherCityError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPublisherStreetError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPublisherEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPublisherPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPublisherPhoneNumberError, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(lblPublisherEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPublisherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublisherNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPublisherCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublisherCountryError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPublisherCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublisherCityError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtPublisherStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPublisherStreetError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPublisherPhoneNumberError)
                        .addComponent(txtPublisherPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPublisherEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublisherEmailError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnNext))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateFields() {
        try {
            
            txtPublisherName.setText(rs.getString("name"));
            txtPublisherCountry.setText(rs.getString("country"));
            txtPublisherCity.setText(rs.getString("city"));
            txtPublisherStreet.setText(rs.getString("street"));
            txtPublisherPhoneNumber.setText(rs.getString("phone_number"));
            txtPublisherEmail.setText(rs.getString("email"));
            // autofill the text boxes with the values retrieved from the database
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeletePublisher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MoveNext() { 
        try {
            // TODO add your handling code here:
            if (!rs.isLast()) {
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeletePublisher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void MovePrevious() {
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeletePublisher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeletePublisher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            // search for games with that publisher
            rs = dbCon.executeStatement("select * from game where publisher_name LIKE '" + txtPublisherName.getText().trim().toUpperCase() + "'") ;
            rs.beforeFirst();
            if(rs.next()) {
                // if any publisher still has a registered game, you cannot delete them
                JOptionPane.showMessageDialog(null, "Cannot delete a publisher that has registered games.");
            }
            else{
                // ask the user if they want to continue
                String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
                confirm += " ";
                if(confirm.equalsIgnoreCase("yes ")) {
                    // delete the publisher
                    String prepSQL = "DELETE publisher WHERE name LIKE '" + txtPublisherName.getText().trim().toUpperCase() + "'";
                    int result = dbCon.executePrepared(prepSQL);
                    if (result > 0) {
                        javax.swing.JLabel label = new javax.swing.JLabel("Publisher " + txtPublisherName.getText().trim().toUpperCase() + " deleted successfully.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        getNewData();
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting publisher.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblPublisherNameError.setText("");
        lblPublisherNameError.setVisible(false);
        lblPublisherCountryError.setText("");
        lblPublisherCountryError.setVisible(false);
        lblPublisherCityError.setText("");
        lblPublisherCityError.setVisible(false);
        lblPublisherStreetError.setText("");
        lblPublisherStreetError.setVisible(false);
        lblPublisherPhoneNumberError.setText("");
        lblPublisherPhoneNumberError.setVisible(false);
        lblPublisherEmailError.setText("");
        lblPublisherEmailError.setVisible(false);
    }

    // checks if the input is an integer
    public boolean isInteger(String s) { 
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // validate all user entry before sending new publisher details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtPublisherName.getText().trim().isEmpty() || (txtPublisherName.getText().trim().length() > 25)) {
            if (txtPublisherName.getText().trim().isEmpty()) {
                lblPublisherNameError.setText("Cannot be empty.");
            } else if ((txtPublisherName.getText().trim().length() > 10)) {
                lblPublisherNameError.setText("Must be < 26 chars.");
            }
            lblPublisherNameError.setVisible(true);
            result = false;
        }

        if (txtPublisherCountry.getText().trim().isEmpty() || (txtPublisherCountry.getText().trim().length() > 25)) {
            if (txtPublisherCountry.getText().trim().isEmpty()) {
                lblPublisherCountryError.setText("Cannot be empty.");
            } else if ((txtPublisherCountry.getText().trim().length() > 10)) {
                lblPublisherCountryError.setText("Must be < 26 chars.");
            }
            lblPublisherCountryError.setVisible(true);
            result = false;
        }
        
        if (txtPublisherCity.getText().trim().isEmpty() || (txtPublisherCity.getText().trim().length() > 25)) {
            if (txtPublisherCity.getText().trim().isEmpty()) {
                lblPublisherCityError.setText("Cannot be empty.");
            } else if ((txtPublisherCity.getText().trim().length() > 10)) {
                lblPublisherCityError.setText("Must be < 26 chars.");
            }
            lblPublisherCityError.setVisible(true);
            result = false;
        }
        
        if (txtPublisherStreet.getText().trim().isEmpty() || (txtPublisherStreet.getText().trim().length() > 25)) {
            if (txtPublisherStreet.getText().trim().isEmpty()) {
                lblPublisherStreetError.setText("Cannot be empty.");
            } else if ((txtPublisherStreet.getText().trim().length() > 10)) {
                lblPublisherStreetError.setText("Must be < 26 chars.");
            }
            lblPublisherStreetError.setVisible(true);
            result = false;
        }

        if (txtPublisherPhoneNumber.getText().trim().isEmpty() || !Pattern.matches("^\\+\\d{3}-\\d{2}-\\d{7}$", txtPublisherPhoneNumber.getText().trim())) {
            if (txtPublisherPhoneNumber.getText().trim().isEmpty()) {
                lblPublisherPhoneNumberError.setText("Cannot be empty.");
            } else {
                lblPublisherPhoneNumberError.setText("Phone number must be in the specified format.");
            }
            lblPublisherPhoneNumberError.setVisible(true);
            result = false;
        }
        
        if (txtPublisherEmail.getText().trim().isEmpty() || (txtPublisherEmail.getText().trim().length() > 25)) {
            if (txtPublisherEmail.getText().trim().isEmpty()) {
                lblPublisherEmailError.setText("Cannot be empty.");
            } else if ((txtPublisherEmail.getText().trim().length() > 10)) {
                lblPublisherEmailError.setText("Must be < 26 chars.");
            }
            lblPublisherEmailError.setVisible(true);
            result = false;
        }

        return result;
    }
    
    private boolean isDuplicate(String publisher_name){
        try {
            // if the user changes the publisher name (the publisher name in the text box is not the same as the publisher name that was shown to the user)
            if(!(publisher_name.trim().equalsIgnoreCase(rs.getString("name").trim()))){
                //check if the publisher name exists in the DB
                
                String stmtSQL = "SELECT name FROM publisher WHERE name LIKE '" + publisher_name + "'";
                ResultSet newRS;
                newRS = dbCon.executeStatement(stmtSQL);
                // isBeforeFirst() returns false if there are no data in the resultset
                return newRS.isBeforeFirst();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteLoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return false;
    }                
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        try {
            if (isValidData() && !isDuplicate(txtPublisherName.getText().trim())) { // if data was valid and publisher name did not change to a new duplicate value
                String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
                confirm += " "; // to ensure confirm is never null
                if(confirm.equalsIgnoreCase("yes ")) {
                    // execute the update statement
                    dbCon.executeStatement("ALTER TABLE game DISABLE CONSTRAINT Game_Publisher_FK");
                    String prepSQL = "UPDATE publisher SET name = " + 
                        "'" + txtPublisherName.getText().trim().toUpperCase() + 
                        "', country = '" + txtPublisherCountry.getText().trim().toUpperCase() +
                        "', city = '" + txtPublisherCity.getText().trim().toUpperCase() +
                        "', street = '" + txtPublisherStreet.getText().trim().toUpperCase() +
                        "', phone_number = '" + txtPublisherPhoneNumber.getText().trim() +
                        "', email = '" + txtPublisherEmail.getText().trim() + "'" +
                        " WHERE name LIKE '" + rs.getString("name") + "'";
                            //the old publisher name, not the one that the user types in
                            //the ResultSet rs contains the info of the publisher name before the update is executed
                    
                    int result = dbCon.executePrepared(prepSQL);
                    if (result > 0) {
                        ResultSet rs2 = dbCon.executeStatement("select * from game where publisher_name LIKE '" + rs.getString("name") + "'");
                        if(rs2.isBeforeFirst()) { // if the publisher had any games we change their respective publisher_name
                            //update the publisher_name of all the games which publisher got updated
                            String prepSQL1 = "UPDATE game SET publisher_name = '" 
                                // set as the new value
                                + txtPublisherName.getText().trim().toUpperCase() + "'"
                                // search for the old value
                                + " WHERE publisher_name LIKE '" + rs.getString("name") + "'";
                            int result1 = dbCon.executePrepared(prepSQL1);
                            if(result1 > 0){
                                // successful update
                                javax.swing.JLabel label = new javax.swing.JLabel("Publisher Name " + txtPublisherName.getText() + " updated successfully for all the games.");
                                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                                getNewData();
                            }
                        }
                        else {
                            javax.swing.JLabel label = new javax.swing.JLabel("Publisher Name " + txtPublisherName.getText() + " updated successfully.");
                            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                            JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                            getNewData();
                        }
                        
                    } else {
                        // check validation errors 
                    }
                    dbCon.executeStatement("ALTER TABLE game ENABLE CONSTRAINT Game_Publisher_FK");
                }
                else{
                    
                }
//                prepStatement.close();
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating publisher." + e.getMessage());

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtPublisherEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPublisherEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPublisherEmailActionPerformed

    private void txtPublisherPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPublisherPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPublisherPhoneNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPublisherCityError;
    private javax.swing.JLabel lblPublisherCountryError;
    private javax.swing.JLabel lblPublisherEmailError;
    private javax.swing.JLabel lblPublisherNameError;
    private javax.swing.JLabel lblPublisherPhoneNumberError;
    private javax.swing.JLabel lblPublisherStreetError;
    private javax.swing.JTextField txtPublisherCity;
    private javax.swing.JTextField txtPublisherCountry;
    private javax.swing.JTextField txtPublisherEmail;
    private javax.swing.JTextField txtPublisherName;
    private javax.swing.JTextField txtPublisherPhoneNumber;
    private javax.swing.JTextField txtPublisherStreet;
    // End of variables declaration//GEN-END:variables
}
