package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class UpdateDeleteGame extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

    public UpdateDeleteGame() {
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);
        
        // set all error labels to invisible
        clearErrorLabels();
        dbCon = new myDBCon();
        getNewData();
    }

    private void getNewData() {

        try {
            rs = dbCon.executeStatement("SELECT * FROM game ORDER BY game_ID ASC");
            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            cmbPublisher.removeAllItems();
            try {
                ResultSet rs1;
                rs1 = dbCon.executeStatement("SELECT name FROM publisher ORDER BY name ASC");
            // populate mgr combo box
            
            while (rs1.next()) {
                cmbPublisher.addItem(rs1.getString("name"));
            }
            rs1.close();
            }
            catch (SQLException e){
                javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected publishers.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
            
            populateFields();
            
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected gameID.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        lblGameIDError = new javax.swing.JLabel();
        lblGameRentalPriceError = new javax.swing.JLabel();
        lblGameTitleError = new javax.swing.JLabel();
        txtGameID = new javax.swing.JTextField();
        txtGameTitle = new javax.swing.JTextField();
        txtGameRentalPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbPublisher = new javax.swing.JComboBox<>();
        jScrollPaneDeveloper = new javax.swing.JScrollPane();
        jListDeveloper = new javax.swing.JList<>();
        jScrollPaneSelectedDeveloper = new javax.swing.JScrollPane();
        jListSelectedDeveloper = new javax.swing.JList<>();
        btnAddDev = new javax.swing.JButton();
        btnRemoveDev = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update/Delete Game");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Game");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Game ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Title");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Rental Price");

        btnUpdate.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        lblGameIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblGameIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblGameIDError.setText("error label");

        lblGameRentalPriceError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblGameRentalPriceError.setForeground(new java.awt.Color(255, 0, 0));
        lblGameRentalPriceError.setText("error label");

        lblGameTitleError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblGameTitleError.setForeground(new java.awt.Color(255, 0, 0));
        lblGameTitleError.setText("error label");

        txtGameID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGameTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGameTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGameTitleActionPerformed(evt);
            }
        });

        txtGameRentalPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGameRentalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGameRentalPriceActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Publisher");

        jScrollPaneDeveloper.setViewportView(jListDeveloper);

        jScrollPaneSelectedDeveloper.setViewportView(jListSelectedDeveloper);

        btnAddDev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddDev.setText("<----");
        btnAddDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDevActionPerformed(evt);
            }
        });

        btnRemoveDev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemoveDev.setText("---->");
        btnRemoveDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDevActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Available Developers");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Selected Developers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGameID, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGameIDError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGameTitleError, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGameRentalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGameRentalPriceError, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addGap(240, 240, 240))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jScrollPaneSelectedDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAddDev)
                                .addComponent(btnRemoveDev))
                            .addGap(22, 22, 22)
                            .addComponent(jScrollPaneDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(101, 101, 101)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext)
                        .addGap(13, 13, 13)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGameIDError)
                            .addComponent(txtGameID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGameTitleError))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtGameRentalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGameRentalPriceError))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneSelectedDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRemoveDev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddDev)
                        .addGap(18, 18, 18)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateFields() {
        try {
            
            txtGameID.setText(rs.getString("game_ID"));
            txtGameTitle.setText(rs.getString("title"));
            txtGameRentalPrice.setText(rs.getString("rental_price"));
            cmbPublisher.setSelectedItem(rs.getString("publisher_name"));
            
            ResultSet rs1 = dbCon.executeStatement("SELECT developer_ID FROM develops WHERE game_ID = " + rs.getString("game_ID") + " ORDER BY developer_ID ASC");
            DefaultListModel<String> selectedDevList = new DefaultListModel<>();
            while (rs1.next()) {
                selectedDevList.addElement(rs1.getString("developer_ID"));
            }
            jListSelectedDeveloper.setModel(selectedDevList);
            rs1.close();
            
            rs1 = dbCon.executeStatement("SELECT developer_ID FROM developer ORDER BY developer_ID ASC");
            DefaultListModel<String> devList = new DefaultListModel<>();
            boolean flag;
            while (rs1.next()) {
                flag = false;
                for (int i = 0; i < selectedDevList.getSize(); i++) {
                    if (rs1.getString("developer_ID").trim().equalsIgnoreCase(selectedDevList.getElementAt(i).trim())) {
                        flag = true;
                        break;
                    }
                }
                if (!flag) devList.addElement(rs1.getString("developer_ID"));
            }
            jListDeveloper.setModel(devList);
            // autofill the text boxes with the values retrieved from the database
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MoveNext() { // selecting the next department and autofilling the textboxes with the gameID values
        try {
            // TODO add your handling code here:
            if (!rs.isLast()) {
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void MovePrevious() { // selecting the prev department and autofilling the textboxes with the dept values
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        // ask the user if they want to continue
        String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
        confirm += " ";
        if(confirm.equalsIgnoreCase("yes ")) {
            try {
                ResultSet rents = dbCon.executeStatement("SELECT * FROM rent_copy where game_ID = " + txtGameID.getText().trim());
                if (!rents.next()) {
                    String prepSQL = "DELETE develops WHERE game_ID = " + txtGameID.getText().trim();
                    int result = dbCon.executePrepared(prepSQL);
                    if (result > 0) {
                        prepSQL = "DELETE game_copy WHERE game_game_ID = " + txtGameID.getText().trim();
                        result = dbCon.executePrepared(prepSQL);
                        if (result > 0) {
                            prepSQL = "DELETE game WHERE game_ID = " + txtGameID.getText().trim();
                            result = dbCon.executePrepared(prepSQL);
                            if (result > 0) {
                                javax.swing.JLabel label = new javax.swing.JLabel("Game ID " + txtGameID.getText().trim() + " deleted successfully.");
                                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                                getNewData();
                            }  
                        }
                    }
                }
                else {
                    JOptionPane.showMessageDialog(null, "Cannot delete a game that is currently being rented by a customer");
                }
               
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error deleting game.");
            }
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    public static void sort(DefaultListModel<String> model) {
        // Step 1: Extract the elements from the DefaultListModel into a list
        List<String> list = new ArrayList<>();
        for (int i = 0; i < model.getSize(); i++) {
            list.add(model.getElementAt(i));
        }

        // Step 2: Sort the list using a custom comparator that parses the strings as integers
        Collections.sort(list, new Comparator<String>() {
            @Override
            public int compare(String o1, String o2) {
                return Integer.compare(Integer.parseInt(o1), Integer.parseInt(o2));
            }
        });

        // Step 3: Clear the DefaultListModel
        model.clear();

        // Step 4: Add the sorted elements back into the DefaultListModel
        for (String element : list) {
            model.addElement(element);
        }
    }
    
    private void clearErrorLabels() { //clear all error labels
        lblGameIDError.setText("");
        lblGameIDError.setVisible(false);
        lblGameTitleError.setText("");
        lblGameTitleError.setVisible(false);
        lblGameRentalPriceError.setText("");
        lblGameRentalPriceError.setVisible(false);
    }

    // checks if the input is an integer
    public boolean isInteger(String s) { 
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    // validate all user entry before sending new game details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtGameID.getText().trim().isEmpty() || !isInteger(txtGameID.getText().trim()) || (Integer.parseInt(txtGameID.getText().trim()) / 1000 > 9)) {
            if (txtGameID.getText().trim().isEmpty()) {
                lblGameIDError.setText("Cannot be empty.");
            } else if (!isInteger(txtGameID.getText().trim())) {
                lblGameIDError.setText("Must be integer.");
            }
            else{
                lblGameIDError.setText("Must be 4 digits at most.");
            }
            lblGameIDError.setVisible(true);
            result = false;
        }

        if (txtGameTitle.getText().trim().isEmpty() || (txtGameTitle.getText().trim().length() > 50)) {
            if (txtGameTitle.getText().trim().isEmpty()) {
                lblGameTitleError.setText("Cannot be empty.");
            } else {
                lblGameTitleError.setText("Must be < 50 chars.");
            }
            lblGameTitleError.setVisible(true);
            result = false;
        }

        if (txtGameRentalPrice.getText().trim().isEmpty() || !(isInteger(txtGameRentalPrice.getText().trim()) || isDouble(txtGameRentalPrice.getText().trim())) || (Double.parseDouble(txtGameRentalPrice.getText().trim()) / 1000 > 9 )) {
            if (txtGameRentalPrice.getText().trim().isEmpty()) {
                lblGameRentalPriceError.setText("Cannot be empty.");
            } else if (!(isInteger(txtGameRentalPrice.getText().trim()) || isDouble(txtGameRentalPrice.getText().trim()))) {
                lblGameRentalPriceError.setText("Must be a number.");
            } 
            else if (Double.parseDouble(txtGameRentalPrice.getText().trim()) / 1000 > 9){
                lblGameRentalPriceError.setText("Must less than 1000.");
            }
            lblGameRentalPriceError.setVisible(true);
            result = false;
        }

        return result;
    }
    
    private boolean isDuplicate(int game_ID) throws SQLException {
        
        try {
            // if the user changes the game_ID (the game_ID in the text box is not the same as the game_ID that was shown to the user)
            if(game_ID != rs.getInt("game_ID")){
                //check if the game_ID exists in the DB
                String stmtSQL = "SELECT game_ID FROM game WHERE game_ID = " + game_ID;
                ResultSet newRS;
                newRS = dbCon.executeStatement(stmtSQL);
                // isBeforeFirst() returns false if there are no data in the resultset
                return newRS.isBeforeFirst();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteLoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }                
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        try {
            if (isValidData() && !isDuplicate(Integer.parseInt(txtGameID.getText().trim()))) { // if data was valid and game_ID did not change to a new duplicate value
                String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
                confirm += " "; // to ensure confirm is never null
                if(confirm.equalsIgnoreCase("yes ")) {
                    dbCon.executeStatement("ALTER TABLE game_copy DISABLE CONSTRAINT Game_copy_Game_FK");
                    // execute the update statement
                    String prepSQL = "UPDATE game SET title = " + 
                            "'" + txtGameTitle.getText().trim().toUpperCase() + 
                            "', rental_price = " + txtGameRentalPrice.getText().trim() +
                            ", publisher_name = '" + cmbPublisher.getSelectedItem().toString() + 
                            "', game_ID = " + txtGameID.getText().trim() +
                            " WHERE game_ID = " + rs.getInt("game_ID");
                            //the old game_ID, not the one that the user types in
                            //the ResultSet rs contains the info of the game_ID before the update is executed
                    
                    int result = dbCon.executePrepared(prepSQL);
                    
                    if (result > 0) {
                       
                        prepSQL = "DELETE develops WHERE game_ID = " + rs.getInt("game_ID");
                        result = dbCon.executePrepared(prepSQL);
                        if (result < 0) {
                            JOptionPane.showMessageDialog(null, "Error removing old developers from the game.");
                        }
                        else {
                            for (int i = 0; i < jListSelectedDeveloper.getModel().getSize(); i++) {
                                String dev_ID = jListSelectedDeveloper.getModel().getElementAt(i);
                                prepSQL = "INSERT INTO develops (game_ID, developer_ID) VALUES ("
                                        + txtGameID.getText().trim()
                                        + ", " + dev_ID.trim() + ")";
                                result = dbCon.executePrepared(prepSQL);
                                if (result < 1) {
                                    JOptionPane.showMessageDialog(null, "Error adding developers to the game.");
                                    break;
                                }
                            }
                        }
                        if (result > 0) {
                            ResultSet rs2 = dbCon.executeStatement("select * from game_copy where game_game_ID = " + rs.getInt("game_ID"));
                            if(rs2.isBeforeFirst()) { 
                                
                                String prepSQL1 = "UPDATE game_copy SET game_game_ID = " + txtGameID.getText().trim() + " WHERE game_game_ID = " + rs.getInt("game_ID");
                                int result1 = dbCon.executePrepared(prepSQL1);
                                if(result1 > 0){
                                    // successful update
                                    javax.swing.JLabel label = new javax.swing.JLabel("Game ID " + txtGameID.getText() + " updated successfully.");
                                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                                    getNewData();
                                }
                            }
                            else {
                                javax.swing.JLabel label = new javax.swing.JLabel("Game ID " + txtGameID.getText() + " updated successfully.");
                                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                                getNewData();
                            }
                        }
                        
                    } else {
                        // check validation errors 
                    }
                    dbCon.executeStatement("ALTER TABLE game_copy ENABLE CONSTRAINT Game_copy_Game_FK");
                }
                else{
                    
                }
//                prepStatement.close();
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating game." + e.getMessage());

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtGameRentalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGameRentalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGameRentalPriceActionPerformed

    private void txtGameTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGameTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGameTitleActionPerformed

    private void btnRemoveDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDevActionPerformed
       
        DefaultListModel<String> selectedDevList = (DefaultListModel<String>) jListSelectedDeveloper.getModel();
        DefaultListModel<String> devList = (DefaultListModel<String>) jListDeveloper.getModel();
        
        for (String selectedValuesList : jListSelectedDeveloper.getSelectedValuesList()) {
            devList.addElement(selectedValuesList);
            selectedDevList.removeElement(selectedValuesList);
        }
        sort(selectedDevList);
        sort(devList);
        jListSelectedDeveloper.setModel(selectedDevList);
        jListDeveloper.setModel(devList);
    }//GEN-LAST:event_btnRemoveDevActionPerformed

    private void btnAddDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDevActionPerformed
        
        DefaultListModel<String> selectedDevList = (DefaultListModel<String>) jListSelectedDeveloper.getModel();
        DefaultListModel<String> devList = (DefaultListModel<String>) jListDeveloper.getModel();
        
        for (String selectedValuesList : jListDeveloper.getSelectedValuesList()) {
            selectedDevList.addElement(selectedValuesList);
            devList.removeElement(selectedValuesList);
        }
        sort(selectedDevList);
        sort(devList);
        jListSelectedDeveloper.setModel(selectedDevList);
        jListDeveloper.setModel(devList);
                
    }//GEN-LAST:event_btnAddDevActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDev;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnRemoveDev;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbPublisher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListDeveloper;
    private javax.swing.JList<String> jListSelectedDeveloper;
    private javax.swing.JScrollPane jScrollPaneDeveloper;
    private javax.swing.JScrollPane jScrollPaneSelectedDeveloper;
    private javax.swing.JLabel lblGameIDError;
    private javax.swing.JLabel lblGameRentalPriceError;
    private javax.swing.JLabel lblGameTitleError;
    private javax.swing.JTextField txtGameID;
    private javax.swing.JTextField txtGameRentalPrice;
    private javax.swing.JTextField txtGameTitle;
    // End of variables declaration//GEN-END:variables
}
