package CMP320Project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class UpdateDeleteLoginUser extends javax.swing.JFrame {

    myDBCon dbCon;
    //string of characters that must be included in the password
    static String chars = "!@#$%^&*()QWERTYUIOPASDFGHJKLZXCVBNM";
    ResultSet rs;
    ResultSet rsUserType; // will be used to fill in the combo box cmbUserType
    boolean togglePassword = true;
    boolean toggleConfirmPassword = true;

    public UpdateDeleteLoginUser() {
        initComponents();
        // center form in screen 
        this.setLocationRelativeTo(null);
        // set all error labels to invisible
        lblNameError.setVisible(false);
        lblUsernameError.setVisible(false);
        lblPasswordError.setVisible(false);
        lblConfirmPasswordError.setVisible(false);
        // connect to db and get user data and populate form fields
        dbCon = new myDBCon();
        getNewData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        cmbUserType = new javax.swing.JComboBox<>();
        btnUpdateUser = new javax.swing.JButton();
        lblUsernameError = new javax.swing.JLabel();
        lblConfirmPasswordError = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();
        lblNameError = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        btnDeleteUser = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        jToggleButtonConfirmPassword = new javax.swing.JToggleButton();
        jToggleButtonPassword = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update/Delete Login User");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Login User");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Confirm Password:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Type:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Name:");

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbUserType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserTypeActionPerformed(evt);
            }
        });

        btnUpdateUser.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdateUser.setText("Update");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        lblUsernameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblUsernameError.setForeground(new java.awt.Color(255, 0, 0));
        lblUsernameError.setText("error label");

        lblConfirmPasswordError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblConfirmPasswordError.setForeground(new java.awt.Color(255, 0, 0));
        lblConfirmPasswordError.setText("error label");

        lblPasswordError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPasswordError.setForeground(new java.awt.Color(255, 0, 0));
        lblPasswordError.setText("error label");

        lblNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblNameError.setText("error label");

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnDeleteUser.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnDeleteUser.setText("Delete");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        jToggleButtonConfirmPassword.setText("On | Off");
        jToggleButtonConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonConfirmPasswordActionPerformed(evt);
            }
        });

        jToggleButtonPassword.setText("On | Off");
        jToggleButtonPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPrevious)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdateUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteUser)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)
                        .addContainerGap(175, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword)
                            .addComponent(txtConfirmPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jToggleButtonConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jToggleButtonPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblConfirmPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblUsernameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsernameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordError)
                    .addComponent(jToggleButtonPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmPasswordError)
                    .addComponent(jToggleButtonConfirmPassword))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateUser)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void getNewData() {
        // get all user data and populate fields 
        try {
            //get the types from the database and store the unique values in the combo box
            rsUserType = dbCon.executeStatement("SELECT type FROM usertype ORDER BY type ASC");
            cmbUserType.removeAllItems();
            while (rsUserType.next()) {
                cmbUserType.addItem(rsUserType.getString("type"));
            }
            rs = dbCon.executeStatement("SELECT name, username, type FROM loginusers ORDER BY type ASC, username ASC");
            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected user type.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void populateFields() {
        // fill in all text boxes apart from the password/confirm password
        try {
            // populate fields with the current user details
            txtName.setText(rs.getString("name"));
            txtUsername.setText(rs.getString("username"));
            clearInputBoxes();
            cmbUserType.setSelectedItem(rs.getString("type"));
            
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteLoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            // enable/disable Previous/Next buttons
            if(rs.isFirst()){
                btnPrevious.setEnabled(false);
            }
            else{
                btnPrevious.setEnabled(true);
            }
            if(rs.isLast()){
                btnNext.setEnabled(false);
            }
            else{
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteLoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void clearErrorLabels() {
        // clear all error labels and set their visibility to false 
        lblNameError.setText("");
        lblNameError.setVisible(false);
        lblUsernameError.setText("");
        lblUsernameError.setVisible(false);
        lblPasswordError.setText("");
        lblPasswordError.setVisible(false);
        lblConfirmPasswordError.setText("");
        lblConfirmPasswordError.setVisible(false);
    }
    
    // used to check if the two strings have a common character
    public static boolean checkCommonCharacter(String str1, String str2) {
        for (int i = 0; i < str1.length(); i++) {
            char c = str1.charAt(i);
            if (str2.indexOf(c) != -1) { //if there is a match
                return true;
            }
        }
        return false;
    }
    
    boolean isValidPassword() {
        // check validity of new password in case of update 
        boolean result = false;
        String password = txtPassword.getText().trim();
        
        //password should be between 5 and 25 characters and must include a special char or a capital letter
        if(password.length() >= 5 && password.length() <= 25 && checkCommonCharacter(password, chars)){
            result = true;
        }
        else{
            if (password.length() > 25) {
                lblPasswordError.setText("Must be less than 26 characters.");
            }
            else if (password.length() < 5){
                lblPasswordError.setText("Must be larger than 4 characters.");
            }
            else {
                lblPasswordError.setText("Must contain {!@#$%^&*()} or a Capital letter.");
            }
        }
        return result;
    }

    boolean isValidData() {
        clearErrorLabels();
        // check validity of new data before update 
        boolean result = true;        
        String name = txtName.getText().trim();
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim();
        String confirmPassword = txtConfirmPassword.getText().trim();
        
        if (name.isEmpty() || (name.length() > 25)) {
            if (name.isEmpty()) {
                lblNameError.setText("Cannot be empty.");
            } else {
                lblNameError.setText("Must be less than 26 characters.");
            }
            lblNameError.setVisible(true);
            result = false;
        }
        
        if (username.isEmpty() || (username.length() > 25)) {
            if (username.isEmpty()) {
                lblUsernameError.setText("Cannot be empty.");
            } else {
                lblUsernameError.setText("Must be less than 26 characters.");
            }
            lblUsernameError.setVisible(true);
            result = false;
        }
        
        if (!password.isEmpty() && !isValidPassword()) {
            // if the user does not type in a new password, then keep the old one

            lblPasswordError.setVisible(true);
            result = false;  
        }
        
        if (!password.isEmpty() && (!(confirmPassword.equals(password)) || confirmPassword.isEmpty())) {
            // if the user does not type in a new password, then keep the old one
            if (confirmPassword.isEmpty()) {
                lblConfirmPasswordError.setText("Must confirm the password.");
                lblConfirmPasswordError.setVisible(true);
                result = false;
            } else {
                // if the twoe passwords don't match
                lblConfirmPasswordError.setText("Must match the password.");
                lblConfirmPasswordError.setVisible(true);
                result = false;
            }
        }
        return result;
    }

    void clearInputBoxes() {
        // make both password text boxes empty
        txtPassword.setText("");
        txtConfirmPassword.setText("");
    }
    
    private boolean isDuplicate(String username){
        try {
            // if the user changes the username (the username in the text box is not the same as the username that was shown to the user)
            if(!(username.equals(rs.getString("username")))){
                //check if the username exists in the DB
                String stmtSQL = "SELECT username FROM loginusers WHERE username = '" + username + "'";
                ResultSet newRS;
                newRS = dbCon.executeStatement(stmtSQL);
                // isBeforeFirst() returns false if there are no data in the resultset
                return newRS.isBeforeFirst();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteLoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return false;
    }

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        // TODO add your handling code here:
        // verify input data
        // verify that new user does not currently exist
            
        try {
            
            // if all the data is valid and the new username does not exist
            if (isValidData() && !isDuplicate(txtUsername.getText().trim())) {                
                // display a popup menu that prompt the user if they are sure to continue
                String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
                confirm += " ";
                // if the user wants to continue
                if(confirm.equalsIgnoreCase("yes ")){
                    // encrypt the password before string it in the DB
                    String password = txtPassword.getText().trim();
                    
                    // store the updated values of the current user
                    String prepSQL = "UPDATE loginusers SET username = " + 
                            "'" + txtUsername.getText().trim() + 
                            "', name = '" + txtName.getText().trim().toUpperCase() + 
                            "', type = " + cmbUserType.getSelectedItem();
                    
                    if (!password.isEmpty()) {
                        String encryptedpassword = AddNewLoginUser.encryptData(password);
                        prepSQL += ", password = '" + encryptedpassword + "'";
                    }
                    
                    prepSQL += " WHERE username = '" + rs.getString("username") + "'";
                    int result = dbCon.executePrepared(prepSQL);
                    if (result > 0) {
                        
                        prepSQL = "UPDATE customer SET name = " + 
                           "'" + txtName.getText().trim().toUpperCase() +
                           "' WHERE name LIKE '" + rs.getString("name") + "'";                                

                        result = dbCon.executePrepared(prepSQL);
                        
                        if (result > 0) {
                            javax.swing.JLabel label = new javax.swing.JLabel("User: " + txtUsername.getText() + " updated successfully.");
                            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                            JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                            if (!cmbUserType.getSelectedItem().equals(rs.getString("type")) && rs.getString("username").equals(LoginForm.currentMenu.luser.username)) { // if the current user's type changed, then the current main menu and update are both closed, and a new menu is generated with the updated user type permissions
                                this.dispose();
                                CustomerMenu newMenu = new CustomerMenu(new LoginUser(LoginForm.currentMenu.luser.username, LoginForm.currentMenu.luser.Name, Integer.parseInt((String) cmbUserType.getSelectedItem())));
                                LoginForm.currentMenu.setVisible(false);
                                LoginForm.currentMenu.dispose();
                                LoginForm.currentMenu = newMenu;
                                LoginForm.currentMenu.setVisible(true);
                            }
                            getNewData();
                        }
                        else {
                           javax.swing.JLabel label = new javax.swing.JLabel("Error updating customer names");
                           label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                           JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE); 
                        }
                        
                    } else {
                        // check validation errors 
                    }
                }
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error updating user." + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:
        try {
            String confirm = JOptionPane.showInputDialog("Are you sure? [Enter \"yes\" to continue]");
            confirm += " ";
            // if the user wants to continue
            if(confirm.equalsIgnoreCase("yes "))
            {
                // delete the current user
                String prepSQL = "DELETE loginusers WHERE username = '" + txtUsername.getText().trim() + "'";
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Login User: " + txtUsername.getText().trim() + " deleted successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    if (txtUsername.getText().trim().equals(LoginForm.currentMenu.luser.username)) { // if the current logged in user was deleted, the program logs out and prompts the user to log in again
                        
                        this.dispose();
                        LoginForm.currentMenu.dispose();
                        (new LoginForm()).setVisible(true); 
                    }
                    getNewData();
                }
                else{
                    javax.swing.JLabel label = new javax.swing.JLabel("Cannot delete user. Ensure that the username exists");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error deleting user.");
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void MoveNext() {
        try {
            // move result set to next record
            if(!rs.isLast()){
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteLoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MovePrevious(){
        try {
            // move result set to next record
            if(!rs.isFirst()){
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteLoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cmbUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUserTypeActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void jToggleButtonPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPasswordActionPerformed
        // TODO add your handling code here:
        if(togglePassword){
            // the first press of the button will be the 'ON' function
            //make password visible
            txtPassword.setEchoChar('\u0000');
            togglePassword = false;
        }
        else{
            // the second press of the button will be the 'OFF' function
            //make password hidden
            txtPassword.setEchoChar('*');
            togglePassword = true;
        }
    }//GEN-LAST:event_jToggleButtonPasswordActionPerformed

    private void jToggleButtonConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonConfirmPasswordActionPerformed
        // TODO add your handling code here:
        if(toggleConfirmPassword){
            // the first press of the button will be the 'ON' function
            //make confirm password visible
            txtConfirmPassword.setEchoChar('\u0000');
            toggleConfirmPassword = false;
        }
        else{
            // the second press of the button will be the 'OFF' function
            //make confirm password hidden
            txtConfirmPassword.setEchoChar('*');
            toggleConfirmPassword = true;
        }
    }//GEN-LAST:event_jToggleButtonConfirmPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButtonConfirmPassword;
    private javax.swing.JToggleButton jToggleButtonPassword;
    private javax.swing.JLabel lblConfirmPasswordError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblUsernameError;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
